
// Solid geometric shapes from Unicode block 25A0-25FF
var myarray = [
    9632,  // ■ BLACK SQUARE
    9650,  // ▲ BLACK UP-POINTING TRIANGLE
    9654,  // ▶ BLACK RIGHT-POINTING TRIANGLE
    9658,  // ► BLACK RIGHT-POINTING POINTER
    9660,  // ▼ BLACK DOWN-POINTING TRIANGLE
    9664,  // ◀ BLACK LEFT-POINTING TRIANGLE
    9668,  // ◄ BLACK LEFT-POINTING POINTER
    9670,  // ◆ BLACK DIAMOND
    9679,  // ● BLACK CIRCLE
    9698,  // ◢ BLACK LOWER RIGHT TRIANGLE
    9699,  // ◣ BLACK LOWER LEFT TRIANGLE
    9700,  // ◤ BLACK UPPER LEFT TRIANGLE
    9701,  // ◥ BLACK UPPER RIGHT TRIANGLE
    9724,  // ◼ BLACK MEDIUM SQUARE
    9726,  // ◾ BLACK MEDIUM SMALL SQUARE
    9642,  // ▪ BLACK SMALL SQUARE
    9652,  // ▴ BLACK UP-POINTING SMALL TRIANGLE
    9656,  // ▸ BLACK RIGHT-POINTING SMALL TRIANGLE
    9662,  // ▾ BLACK DOWN-POINTING SMALL TRIANGLE
    9666,  // ◂ BLACK LEFT-POINTING SMALL TRIANGLE
    9646,  // ▮ BLACK VERTICAL RECTANGLE
    9644,  // ▬ BLACK RECTANGLE
    9648,  // ▰ BLACK PARALLELOGRAM
    9673,  // ◉ FISHEYE
    9678,  // ◎ BULLSEYE
    9636,  // ▤ SQUARE WITH HORIZONTAL FILL
    9637,  // ▥ SQUARE WITH VERTICAL FILL
    9638,  // ▦ SQUARE WITH ORTHOGONAL CROSSHATCH FILL
    9639,  // ▧ SQUARE WITH UPPER LEFT TO LOWER RIGHT FILL
    9640,  // ▨ SQUARE WITH UPPER RIGHT TO LOWER LEFT FILL
    9641,  // ▩ SQUARE WITH DIAGONAL CROSSHATCH FILL
    9677,  // ◍ CIRCLE WITH VERTICAL FILL
    9703,  // ◧ SQUARE WITH LEFT HALF BLACK
    9704,  // ◨ SQUARE WITH RIGHT HALF BLACK
    9705,  // ◩ SQUARE WITH UPPER LEFT DIAGONAL HALF BLACK
    9706,  // ◪ SQUARE WITH LOWER RIGHT DIAGONAL HALF BLACK
    9709,  // ◭ UP-POINTING TRIANGLE WITH LEFT HALF BLACK
    9710   // ◮ UP-POINTING TRIANGLE WITH RIGHT HALF BLACK
];
