var block_lang['Adlam'] = ['adlam'];
var block_lang['Aegean_Numbers'] = ['sanslinearb'];
var block_lang['Ahom'] = ['ahom'];
var block_lang['Alchemical_Symbols'] = ['symbols'];
//var block_lang['Alphabetic_Presentation_Forms'] = ['']; //armenian/latin/hebrew requires special processing
var block_lang['Anatolian_Hieroglyphs'] = ['anatolianheiroglyphics'];
var block_lang['Ancient_Greek_Musical_Notation'] = ['music'];
var block_lang['Ancient_Greek_Numbers'] = ['symbols2'];
var block_lang['Ancient_Symbols'] = ['symbols2'];
var block_lang['Arabic'] = ['arabic'];
var block_lang['Arabic_Extended_A'] = ['arabic'];
var block_lang['Arabic_Mathematical_Alphabetic_Symbols'] = ['arabic'];
var block_lang['Arabic_Presentation_Forms_A'] = ['arabic-ext'];
var block_lang['Arabic_Presentation_Forms_B'] = ['arabic-ext'];
var block_lang['Arabic_Supplement'] = ['arabic-ext'];
var block_lang['Armenian'] = ['armenian'];
var block_lang['Arrows'] = ['symbols'];
var block_lang['Avestan'] = ['avestan'];
var block_lang['Balinese'] = ['balinese'];
var block_lang['Bamum'] = ['bamum'];
var block_lang['Bamum_Supplement'] = ['bamum'];
var block_lang['Basic_Latin'] = ['latin'];
var block_lang['Bassa_Vah'] = ['bassa-vah'];
var block_lang['Batak'] = ['batak'];
var block_lang['Bengali'] = ['bengali'];
var block_lang['Bhaiksuki'] = ['bhaiksuki'];
var block_lang['Block_Elements'] = ['noto-mono'];
var block_lang['Bopomofo'] = ['noto-simple-chinese','noto-trad-chinese','noto-hongkong','noto-korean','noto-japanese']; 
var block_lang['Bopomofo_Extended'] = ['noto-simple-chinese','noto-trad-chinese','noto-hongkong','noto-korean','noto-japanese']; 
var block_lang['Box_Drawing'] = ['symbols'];
var block_lang['Brahmi'] = ['brahmi'];
var block_lang['Braille_Patterns'] = ['symbols'];
var block_lang['Buginese'] = ['buginese'];
var block_lang['Buhid'] = ['buhid'];
var block_lang['Byzantine_Musical_Symbols'] = ['music'];
var block_lang['Carian'] = ['carion'];
var block_lang['Caucasian_Albanian'] = ['caucasian-albanian'];
var block_lang['Chakma'] = ['chakma'];
var block_lang['Cham'] = ['cham'];
var block_lang['Cherokee'] = ['cherokee'];
var block_lang['Cherokee_Supplement'] = ['cherokee'];
var block_lang['Chess_Symbols'] = ['symbols'];
//var block_lang['CJK_Compatibility'] = ['chinese-simplified'];
//var block_lang['CJK_Compatibility_Forms'] = ['chinese-simplified','chinese-traditional','chinese-hongkong'];
//var block_lang['CJK_Compatibility_Ideographs'] = ['chinese-simplified','chinese-traditional','chinese-hongkong'];
var block_lang['CJK_Radicals_Supplement'] = ['chinese-simplified','chinese-traditional','chinese-hongkong'];
var block_lang['CJK_Strokes'] = ['chinese-simplified','chinese-traditional','chinese-hongkong'];
var block_lang['CJK_Symbols_And_Punctuation'] = ['chinese-simplified','chinese-traditional','chinese-hongkong'];
//var block_lang['CJK_Unified_Ideographs'] = ['chinese-simplified','chinese-traditional','chinese-hongkong'];
//var block_lang['CJK_Unified_Ideographs_Extension_A'] = ['chinese-simplified','chinese-traditional','chinese-hongkong'];
//var block_lang['Combining_Diacritical_Marks_Extended'] = ['latin','latin-ext'];
//var block_lang['Combining_Diacritical_Marks_For_Symbols'] = ['latin','latin-ext'];
var block_lang['Common_Indic_Number_Forms'] = ['noto-devanagari'];
//var block_lang['Control_Pictures'] = ['symbols2'];
var block_lang['Coptic'] = ['coptic'];
var block_lang['Coptic_Epact_Numbers'] = ['coptic','symbols2'];
var block_lang['Counting_Rod_Numerals'] = ['symbols'];
var block_lang['Cuneiform'] = ['cuneiform'];
var block_lang['Cuneiform_Numbers_And_Punctuation'] = ['cuneiform'];
var block_lang['Currency_Symbols'] = ['symbols'];
var block_lang['Cypriot_Syllabary'] = ['cypriot'];
var block_lang['Cyrillic'] = ['cyrillic'];
var block_lang['Cyrillic_Extended_B'] = ['cyrillic-ext'];
var block_lang['Cyrillic_Extended_C'] = ['cyrillic-ext'];
var block_lang['Cyrillic_Supplement'] = ['cyrillic-ext'];
var block_lang['Deseret'] = ['deseret'];
var block_lang['Devanagari'] = ['devanagari'];
var block_lang['Devanagari_Extended'] = ['devanagari'];
var block_lang['Dingbats'] = ['symbols'];
var block_lang['Dogra'] = ['dogra'];
var block_lang['Domino_Tiles'] = ['symbols'];
var block_lang['Duployan'] = ['duployan'];
var block_lang['Early_Dynastic_Cuneiform'] = ['cuneiform'];
var block_lang['Egyptian_Hieroglyphs'] = ['egyptianheiroglyphics'];
var block_lang['Elbasan'] = ['elbasan'];
var block_lang['Elymaic'] = ['elymaic'];
var block_lang['Emoticons'] = ['symbols'];
var block_lang['Enclosed_Alphanumeric_Supplement'] = ['symbols'];
var block_lang['Enclosed_Alphanumerics'] = ['symbols'];
//var block_lang['Enclosed_CJK_Letters_And_Months'] = [''];
//var block_lang['Enclosed_Ideographic_Supplement'] = [''];
var block_lang['Ethiopic'] = ['ethiopic'];
var block_lang['Ethiopic_Extended'] = ['ethiopic'];
var block_lang['Ethiopic_Extended_A'] = ['ethiopic'];
var block_lang['Ethiopic_Supplement'] = ['ethiopic'];
var block_lang['General_Punctuation'] = ['symbols'];
var block_lang['Geometric_Shapes'] = ['symbols'];
var block_lang['Geometric_Shapes_Extended'] = ['symbols'];
var block_lang['Georgian'] = ['georgian'];
var block_lang['Georgian_Extended'] = ['georgian'];
var block_lang['Georgian_Supplement'] = ['georgian'];
var block_lang['Glagolitic'] = ['glagolitic'];
var block_lang['Gothic'] = ['gothic'];
var block_lang['Grantha'] = ['grantha'];
var block_lang['Greek_And_Coptic'] = ['coptic','latin-ext'];
var block_lang['Greek_Extended'] = ['latin-ext'];
var block_lang['Gujarati'] = ['gujarati'];
var block_lang['Gunjala_Gondi'] = ['gunjala-gondi'];
var block_lang['Gurmukhi'] = ['gurmukhi'];
//var block_lang['Halfwidth_And_Fullwidth_Forms'] = [''];
var block_lang['Hangul_Compatibility_Jamo'] = ['korean'];
var block_lang['Hangul_Jamo'] = ['korean'];
var block_lang['Hangul_Jamo_Extended_A'] = ['korean'];
var block_lang['Hangul_Jamo_Extended_B'] = ['korean'];
var block_lang['Hangul_Syllables'] = ['korean'];
var block_lang['Hanifi_Rohingya'] = ['hanifi-rohingya'];
var block_lang['Hanunoo'] = ['hunanoo'];
var block_lang['Hatran'] = ['hatron'];
var block_lang['Hebrew'] = ['hebrew'];
var block_lang['Hentaigana'] = ['hentaigana']
var block_lang['Hiragana'] = ['japanese'];
//var block_lang['Ideographic_Description_Characters'] = [''];
//var block_lang['Ideographic_Symbols_And_Punctuation'] = [''];
var block_lang['Imperial_Aramaic'] = ['imperial_aramaic'];
var block_lang['Indic_Siyaq_Numbers'] = ['indic-siyaq-numbers'];
var block_lang['Inscriptional_Pahlavi'] = ['inscriptionalpahlavi'];
var block_lang['Inscriptional_Parthian'] = ['inscriptionalparthian'];
var block_lang['IPA_Extensions'] = ['noto-regular'];
var block_lang['Javanese'] = ['javanese'];
var block_lang['Kaithi'] = ['kaithi'];
var block_lang['Kannada'] = ['kannada'];
var block_lang['Katakana'] = ['japanese'];
var block_lang['Katakana_Phonetic_Extensions'] = ['japanese'];
var block_lang['Kayah_Li'] = ['kayahli'];
var block_lang['Kharoshthi'] = ['kharoshthi'];
var block_lang['Khmer'] = ['khmer'];
var block_lang['Khmer_Symbols'] = ['khmer'];
var block_lang['Khojki'] = ['khojki'];
var block_lang['Khudawadi'] = ['khudawadi'];
var block_lang['Lao'] = ['lao'];
var block_lang['Latin_1_Supplement'] = [''];
var block_lang['Latin_Extended_A'] = [''];
var block_lang['Latin_Extended_Additional'] = [''];
var block_lang['Latin_Extended_B'] = ['latin_extended_b'];
var block_lang['Latin_Extended_C'] = ['latin_extended_c'];
var block_lang['Latin_Extended_D'] = ['latin_extended_d'];
var block_lang['Latin_Extended_E'] = ['latin_extended_e'];
var block_lang['Latin_Extended_F'] = ['latin_extended_f']; //unicode 14
var block_lang['Latin_Extended_G'] = ['latin_extended_g']; //unicode 14
var block_lang['Lepcha'] = ['lepcha'];
var block_lang['Letterlike_Symbols'] = ['noto-regular'];
var block_lang['Limbu'] = ['limbu'];
var block_lang['Linear_A'] = ['lineara'];
var block_lang['Linear_B_Ideograms'] = ['linearb'];
var block_lang['Linear_B_Syllabary'] = ['linearb'];
var block_lang['Lisu'] = ['lisu'];
var block_lang['Lisu_Supplement'] = ['lisu'];
var block_lang['Lycian'] = ['lycian'];
var block_lang['Lydian'] = ['lydian'];
var block_lang['Mahajani'] = ['mahajani'];
var block_lang['Mahjong_Tiles'] = ['symbols'];
var block_lang['Makasar'] = ['makasar'];
var block_lang['Malayalam'] = ['malayalam'];
var block_lang['Mandaic'] = ['mandaic'];
var block_lang['Manichaean'] = ['manichaean'];
var block_lang['Marchen'] = ['marchen'];
var block_lang['Masaram_Gondi'] = ['masaram-gondi'];
var block_lang['Mathematical_Alphanumeric_Symbols'] = ['symbols'];
var block_lang['Mathematical_Operators'] = ['symbols'];
var block_lang['Mayan_Numerals'] = ['mayan-numerals'];
var block_lang['Medefaidrin'] = ['medefaidrin'];
var block_lang['Meetei_Mayek'] = ['meeteimayek'];
var block_lang['Meetei_Mayek_Extensions'] = ['meeteimayek'];
var block_lang['Mende_Kikakui'] = ['mende_kikakui'];
var block_lang['Meroitic_Cursive'] = ['meroitic'];
var block_lang['Meroitic_Hieroglyphs'] = ['meroitic'];
var block_lang['Miao'] = ['miao'];
var block_lang['Miscellaneous_Mathematical_Symbols_A'] = ['symbols'];
var block_lang['Miscellaneous_Mathematical_Symbols_B'] = ['symbols'];
var block_lang['Miscellaneous_Symbols'] = ['symbols'];
var block_lang['Miscellaneous_Symbols_And_Arrows'] = ['symbols'];
var block_lang['Miscellaneous_Symbols_And_Pictographs'] = ['symbols'];
var block_lang['Miscellaneous_Technical'] = ['symbols'];
var block_lang['Modi'] = ['modi'];
var block_lang['Modifier_Tone_Letters'] = ['noto-regular'];
var block_lang['Mongolian'] = ['mongolian'];
var block_lang['Mongolian_Supplement'] = ['mongolian'];
var block_lang['Mro'] = ['mro'];
var block_lang['Multani'] = ['multani'];
var block_lang['Musical_Symbols'] = ['symbols'];
var block_lang['Myanmar'] = ['myanmar'];
var block_lang['Myanmar_Extended_A'] = ['myanmar'];
var block_lang['Myanmar_Extended_B'] = ['myanmar'];
var block_lang['Nabataean'] = ['nabataean'];
var block_lang['Nandinagari'] = ['nandinagari'];
var block_lang['New_Tai_Lue'] = ['newthailue'];
var block_lang['Newa'] = ['newa'];
var block_lang['NKo'] = ['nko'];
var block_lang['Number_Forms'] = ['symbols'];
var block_lang['Nushu'] = ['nushu'];
var block_lang['Nyiakeng_Puachue_Hmong'] = ['nyiakeng-puachue-hmong'];
var block_lang['Ogham'] = ['ogham'];
var block_lang['Ol_Chiki'] = ['olchiki'];
var block_lang['Old_Hungarian'] = ['old-hungarian'];
var block_lang['Old_Italic'] = ['olditalic'];
var block_lang['Old_North_Arabian'] = ['old-north-arabian'];
var block_lang['Old_Permic'] = ['old-permic'];
var block_lang['Old_Persian'] = ['oldpersian'];
var block_lang['Old_South_Arabian'] = ['oldsoutharabian'];
var block_lang['Old_Turkic'] = ['oldturkic'];
var block_lang['Optical_Character_Recognition'] = ['symbols'];
var block_lang['Oriya'] = ['oriya'];
var block_lang['Ornamental_Dingbats'] = ['symbols'];
var block_lang['Osage'] = ['osage'];
var block_lang['Osmanya'] = ['osmanya'];
var block_lang['Ottoman_Siyaq_Numbers'] = ['ottoman-siyaq-numbers'];
var block_lang['Pahawh_Hmong'] = ['pahawh-hmong'];
var block_lang['Palmyrene'] = ['palmyrene'];
var block_lang['Pau_Cin_Hau'] = ['pau-cin-hau'];
var block_lang['Phags_Pa'] = ['phagspa'];
var block_lang['Phaistos_Disc'] = ['symbols2'];
var block_lang['Phoenician'] = ['phoenician'];
var block_lang['Phonetic_Extensions'] = ['noto-regular'];
var block_lang['Phonetic_Extensions_Supplement'] = ['noto-regular'];
var block_lang['Playing_Cards'] = ['symbols'];
var block_lang['Psalter_Pahlavi'] = ['psalter-pahlavi'];
var block_lang['Rejang'] = ['rejang'];
var block_lang['Rumi_Numeral_Symbols'] = ['symbols2'];
var block_lang['Runic'] = ['symbols'];
var block_lang['Samaritan'] = ['samaritan'];
var block_lang['Saurashtra'] = ['saurashtra'];
var block_lang['Sharada'] = ['sharada'];
var block_lang['Shavian'] = ['shavian'];
var block_lang['Siddham'] = ['siddham'];
var block_lang['Sinhala'] = ['sinhala'];
var block_lang['Sinhala_Archaic_Numbers'] = ['sinhala'];
//var block_lang['Small_Form_Variants'] = ['small-kana'];  //redundant lots of cjk fonts including japanese
//var block_lang['Small_Kana_Extension'] = ['small-kana']; //review maybe japanese
//var block_lang['Kana_Extended_B'] = ['small-kana']; //review maybe japanese
var block_lang['Kana_Extended_A'] = ['hentaigana'];
var block_lang['Kana_Supplement'] = ['hentaigana'];
var block_lang['Kanbun'] = ['japanese'];
var block_lang['Kangxi_Radicals'] = ['japanese'];
var block_lang['Sogdian'] = ['sogdian'];
var block_lang['Old_Sogdian'] = ['old-sogdian'];
var block_lang['Sora_Sompeng'] = ['sora-sompeng'];
var block_lang['Soyombo'] = ['soyombo'];
var block_lang['Spacing_Modifier_Letters'] = ['symbols'];
var block_lang['Sundanese'] = ['sudanese'];
var block_lang['Sundanese_Supplement'] = ['sudanese'];
var block_lang['Superscripts_And_Subscripts'] = ['symbols'];
var block_lang['Supplemental_Arrows_A'] = ['symbols'];
var block_lang['Supplemental_Arrows_B'] = ['symbols'];
var block_lang['Supplemental_Arrows_C'] = ['symbols'];
var block_lang['Supplemental_Mathematical_Operators'] = ['symbols'];
var block_lang['Supplemental_Punctuation'] = ['symbols'];
var block_lang['Supplemental_Symbols_And_Pictographs'] = ['symbols'];
var block_lang['Sutton_SignWriting'] = ['signwriting'];
var block_lang['Syloti_Nagri'] = ['sylotinagri'];
var block_lang['Symbols_And_Pictographs_Extended_A'] = ['symbols'];
var block_lang['Syriac'] = ['syriaceastern','syriacestrangela','syriacwestern'];
var block_lang['Syriac_Supplement'] = ['syriaceastern','syriacestrangela','syriacwestern'];
var block_lang['Tagalog'] = ['tagalog'];
var block_lang['Tagbanwa'] = ['tagbanwa'];
var block_lang['Tai_Le'] = ['taile'];
var block_lang['Tai_Tham'] = ['thaitham'];
var block_lang['Tai_Viet'] = ['thaiviet'];
var block_lang['Tai_Xuan_Jing_Symbols'] = ['symbols'];
var block_lang['Takri'] = ['takri'];
var block_lang['Tamil'] = ['tamil'];
var block_lang['Tamil_Supplement'] = ['tamil'];
var block_lang['Tangut'] = ['tangut'];
var block_lang['Tangut_Components'] = ['tangut'];
var block_lang['Telugu'] = ['telegu'];
var block_lang['Thaana'] = ['thaana'];
var block_lang['Thai'] = ['thai'];
var block_lang['Tibetan'] = ['tibetan'];
var block_lang['Tifinagh'] = ['tifinagh'];
var block_lang['Tirhuta'] = ['tirhuta'];
var block_lang['Transport_And_Map_Symbols'] = ['symbols'];
var block_lang['Ugaritic'] = ['ugaritic'];
var block_lang['Unified_Canadian_Aboriginal_Syllabics'] = ['canadianaboriginal'];
var block_lang['Unified_Canadian_Aboriginal_Syllabics_Extended'] = ['canadianaboriginal'];
var block_lang['Vai'] = ['vai'];
var block_lang['Vedic_Extensions'] = ['noto-devanagari'];
var block_lang['Vertical_Forms'] = ['symbols'];
var block_lang['Wancho'] = ['wancho'];
var block_lang['Warang_Citi'] = ['warangciti'];
var block_lang['Yi_Radicals'] = ['yi'];
var block_lang['Yi_Syllables'] = ['yi'];
var block_lang['Yijing_Hexagram_Symbols'] = ['symbols'];
var block_lang['Zanabazar_Square'] = ['zanabazar-square'];
//unicode 13
var block_lang['Yezidi'] = ['yezidi'];
var block_lang['Chorasmian'] = ['chorasmian'];
var block_lang['Dives_Akiru'] = ['dives-akiru'];
var block_lang['Khitan_Small_Script'] = ['khitan-small-script'];
var block_lang['Symbols_For_Legacy_Computing'] = ['symbols2'];
var block_lang['Lisu_Supplement'] = ['lisu'];
var block_lang['Tangut_Supplement'] = ['tangut'];

//unicode 14
var block_lang['Arabic_Extended_B'] = ['noto-arabic'];
var block_lang['Vithkuqi'] = ['vithkuqi'];
var block_lang['Old_Uyghur'] = ['old-uyghur'];
var block_lang['Unified_Canadian_Aboriginal_Syllabics_Extended_A'] = ['canadianaboriginal'];
var block_lang['Cypro-Minoan'] = ['cyprominoan'];
var block_lang['Tangsa'] = ['tangsa'];
var block_lang['Kana_Extended_B'] = ['kana-extended-b'];
var block_lang['Znamenny_Musical_Notation'] = ['znamenny-musical-notation'];
var block_lang['Toto'] = ['toto'];
var block_lang['Ethiopic_Extended_B'] = ['noto-ethiopic'];
//unicode 15
var block_lang['Arabic_Extended_C'] = ['noto-arabic'];
var block_lang['Devanagari_Extended_A'] = ['noto-devanagari'];
var block_lang['Kawi'] = ['kawi']; //Noto Sans Kawi
var block_lang['Kaktovik Numerals'] = ['symbols2'];
//var block_lang['Cyrillic_Extended_D'] = ['noto-cyrillic']; No coverage
var block_lang['Nag_Mundari'] = ['nag-mundari']; 


//Unicode 16
block_lang['Todhri'] = [ "todhri" ]
//block_lang['Garay'] = [ "garay" ]
//block_lang['Tulu_Tigalari'] = [ "tulu-tigalari" ]
//block_lang['Myanmar_Extended_C'] = [ "noto-myanmar" ]
block_lang['Sunuwar'] = [ "sunawar" ]
//block_lang['Egyptian_Hieroglyphs_Extended_A'] = [ "egyptianheiroglyphics" ]
//block_lang['Gurung_Khema'] = [ "gurung-khema" ]
//block_lang['Kirat_Rai'] = [ "kirat-rai" ]
block_lang['Symbols_for_Legacy_Computing_Supplement'] = [ "symbols2" ]
//block_lang['Ol_Onal'] = [ "ol-onal" ]

//Unicode 17
//block_lang['Sidetic'] = [ "sidetic" ]
//block_lang['Sharada_Supplement'] = [ "sharada" ]
//block_lang['Tolong_Siki'] = [ "tolong-siki" ]
//block_lang['Beria_Erfe'] = [ "beria-erfe" ]
//block_lang['Tangut_Components_Supplement'] = [ "tangut" ]
//block_lang['Miscellaneous_Symbols_Supplement'] = [ "symbols2" ]
//block_lang['Tai_Yo'] = [ "tai-yo" ]

//Unicode 13
lang_font['khitan-small-script'] = [ 
  "Noto Serif Khitan Small Script",
  "Noto Fangsong KSS Rotated-local",
  "Noto Fangsong KSS Vertical-local"
]
lang_font['yezidi'] = [	"Noto Serif Yezidi" ]
lang_font['chorasmian'] = [ "Noto Sans Chorasmian" ]
lang_font['dives_akiru'] = [ "Noto Serif Dives Akiru" ]


//Unicode 14
lang_font['vithkuqi'] = [ "Noto Sans Vithkuqi" ]
lang_font['old_uyghur'] = [ "Noto Serif Old Uyghur" ]
lang_font['cyprominoan'] = [ "Noto Sans Cypro Minoan" ]
lang_font['tangsa'] = [ "Noto Sans Tangsa" ]
//lang_font['kana-extended-b'] = [ "" ] //no coverage
lang_font['znamenny-musical-notation'] = [ "Noto Znamenny Musical Notation" ]
lang_font['toto'] = [ "Noto Serif Toto" ]

//Unicode 15
lang_font['kawi'] = [ "Noto Sans Kawi" ]
lang_font['nag-mundari'] = [ "Noto Sans Nag Mundari" ]

//Unicode 16
lang_font['todhri'] = [ "Noto Serif Todhri" ]
//lang_font['garay'] = [ "" ]
//lang_font['tulu-tigalari'] = [ "" ]
lang_font['sunuwar'] = [ "Noto Sans Sunuwar" ] 
//lang_font['gurung-khema'] = [ "Noto Sans Gurung Khema" ] //started
//lang_font['kirat-rai'] = [ "" ]
//lang_font['ol-onal'] = [ "Noto Sans Ol Onal" ] //started

//Unicode17
//lang_font['sidetic'] = [ "" ]
//lang_font['tolong-siki'] = [ "" ]
//lang_font['beria-erfe'] = [ "" ]
//lang_font['tai-yo'] = [ "" ]

//Before Unicode 13
//New Noto Fonts since 2020
lang_font['hentaigana'] = ["Noto Serif Hentaigana"]
lang_font['zanabazar-square'] = [ "Noto Sans Zanabazar Square" ]
lang_font['yi'] = [ "Noto Sans Yi" ]
lang_font['warangciti'] = [ "Noto Sans Warang Citi"  ]
lang_font['wancho'] = [ "Noto Sans Wancho"  ]
lang_font['noto-devanagari'] = [  //has complexity all but a few are covered by devanagari
  "Noto Serif Devanagari",
  "Noto Sans Devanagari"
]
lang_font['tirhuta'] = [ "Noto Sans Tirhuta" ]
lang_font['tangut'] = [ "Noto Serif Tangut"  ]
lang_font['takri'] = [ "Noto Sans Takri"  ]
lang_font['signwriting'] = [ "Noto Sans Sign Writing" ]
lang_font['soyombo'] = [ "Noto Sans Soyombo" ]
lang_font['sora-sompeng'] = [ "Noto Sans Sora Sompeng" ]
lang_font['sogdian'] = ["Noto Sans Sogdian-local" ] //not yes hosted review
lang_font['old-sogdian'] = [ "Noto Sans Old Sogdian-local" ] //not yet hosted review
lang_font['batak'] = [ "Noto Sans Batak" ]
lang_font['siddham'] = [ "Noto Sans Siddham" ]
lang_font['sharada'] = [ "Noto Sans Sharada" ]
lang_font['psalter-pahlavi'] = [ "Noto Sans Psalter Pahlavi" ]
lang_font['noto-regular'] = [ "Noto Sans","Noto Mono","Noto Serif", "Noto Serif Display" ]
lang_font['noto-regular-no-display'] = [ "Noto Sans","Noto Mono","Noto Serif" ]
lang_font['noto-mono'] = [ "Noto Mono" ]
lang_font['ottoman-siyaq-numbers'] = [ "Noto Sans Indic Siyaq Numbers"  ]
lang_font['pahawh-hmong'] = [ "Noto Sans Pahawh Hmong"  ]
lang_font['palmyrene'] = [ "Noto Sans Palmyrene"  ]
lang_font['pau-cin-hau'] = [ "Noto Sans Pau Cin Hau"  ]
lang_font['osage'] = [ "Noto Sans Osage" ]
lang_font['old-hungarian'] = [ "Noto Sans Old Hungarian"  ]
lang_font['old-north-arabian'] = [ "Noto Sans Old North Arabian"  ]
lang_font['old-permic'] = [ "Noto Sans Old Permic"  ]
lang_font['nabataean'] = [ "Noto Sans Nabataean" ]
lang_font['nandinagari'] = [ "Noto Sans Nandinagari" ]
lang_font['newa'] = [ "Noto Sans Newa"  ]
lang_font['nko'] = [ "Noto Sans NKo Unjoined","Noto Sans NKo" ]
lang_font['nushu'] = [ "Noto Traditional Nushu", "Noto Sans Nushu" ]
lang_font['nyiakeng-puachue-hmong'] = [ "Noto Serif Nyiakeng Puachue Hmong" ]
lang_font['mende-kikakui'] = [ "Noto Sans Mende Kikakui" ]
lang_font['meroitic'] = [ "Noto Sans Meroitic" ]
lang_font['miao'] = [ "Noto Sans Miao" ]
lang_font['modi'] = [ "Noto Sans Modi" ]
lang_font['mro'] = [ "Noto Sans Mro" ]
lang_font['multani'] = [ "Noto Sans Multani" ]
lang_font['mahajani'] = [ "Noto Sans Mahajani" ]
lang_font['makasar'] = [ "Noto Serif Makasar" ]
lang_font['manichaean'] = [ "Noto Sans Manichaean" ]
lang_font['marchen'] = [ "Noto Sans Marchen" ]
lang_font['masaram-gondi'] = [ "Noto Sans Masaram Gondi" ]
lang_font['mayan-numerals'] = [ "Noto Sans Mayan Numerals" ]
lang_font['medefaidrin'] = [ "Noto Sans Medefaidrin" ]
lang_font['khojki'] = [ "Noto Sans Khojki" ]
lang_font['khudawadi'] = [ "Noto Sans Khudawadi" ]
lang_font['limbu'] = [ "Noto Sans Limbu" ]
lang_font['lycian'] = [ "Noto Sans Lycian" ]
lang_font['imperial_aramaic'] = [ "Noto Sans Imperial Aramaic" ]
lang_font['indic-siyaq-numbers'] = [ "Noto Sans Indic Siyaq Numbers" ]
lang_font['hatron'] = [ "Noto Sans Hatran" ]
lang_font['hanifi-rohingya'] = [ "Noto Sans Hanifi Rohingya" ]
lang_font['gunjala-gondi'] = [ "Noto Sans Gunjala Gondi" ]
lang_font['grantha'] = [ "Noto Sans Grantha" ]
lang_font['glagolitic'] = [ "Noto Sans Glagolitic" ]
lang_font['elymaic'] = [ "Noto Sans Elymaic" ]
lang_font['elbasan'] = [ "Noto Sans Elbasan" ]
lang_font['duployan'] = [ "Noto Sans Duployan" ]
lang_font['dogra'] = [ "Noto Serif Dogra" ]
lang_font['caucasian-albanian'] = [ "Noto Sans Caucasian Albanian" ]
lang_font['chakma'] = [ "Noto Sans Chakma" ]
lang_font['bhaiksuki'] = [ "Noto Sans Bhaiksuki" ]
lang_font['bassa-vah'] = [ "Noto Sans Bassa Vah" ]
lang_font['music'] = [ "Noto Music" ]
lang_font['adlam'] = [
  "ADLaM Display"
  "Google Sans Code"
  "Noto Sans Adlam"
  "Noto Sans Adlam Unjoined"
]
lang_font['ahom'] = [ "Noto Serif Ahom"]
lang_font['linearb'] = [ "Noto Sans Linear B" ]
lang_font['lineara'] = [ "Noto Sans Linear A" ]

//Before Unicode 13
lang_font['tagalog'] = ["Noto Sans Tagalog" ]
lang_font['noto-ethiopic'] = [ 
  "Noto Serif Ethiopic",            
	"Noto Sans Ethiopic"
 ]
lang_fong['ethiopic'] = [
  "Abyssinica SIL",
  "Agbalumo",
  "Menbere",
  "Noto Sans Ethiopic",
  "Noto Serif Ethiopic"
 ] 
 lang_font['carian'] = [ "Noto Sans Carian" ]
lang_font['inscriptionalpahlavi'] = [ "Noto Sans Inscriptional Pahlavi" ]
lang_font['javanese'] = [ "Noto Sans Javanese" ]
lang_font['batak'] = ["Noto Sans Batak"]
lang_font['phoenician'] = ["Noto Sans Phoenician"]
lang_font['kayahli'] = ["Noto Sans Kayahli"]
lang_font['rejang'] = ["Noto Sans Rejang"]  
lang_font['lepcha'] = ["Noto Sans Lepcha"]
lang_font['thaana'] = ["Noto Sans Thaana"] 
lang_font['gothic'] = ["Noto Sans Gothic"] 
lang_font['sudanese'] = ["Noto Sans Sundanese" ]           
lang_font['samaritan'] = ["Noto Sans Samaritan"]
lang_font['brahmi'] = ["Noto Sans Brahmi"] 
lang_font['olchiki'] = ["Noto Sans Olchiki"] 
lang_font['shavian'] = ["Noto Sans Shavian"]         
lang_font['tagbanwa'] = ["Noto Sans Tagbanwa"]           
lang_font['oldturkic'] = ["Noto Sans Oldturkic"]                    
lang_font['tifinagh'] = ["Noto Sans Tifinagh"]             
lang_font['deseret'] = ["Noto Sans Deseret"]           
lang_font['cypriot'] = ["Noto Sans Cypriot"]
lang_font['olditalic'] = ["Noto Sans Old Italic"]
lang_font['avestan'] = ["Noto Sans Avestan"]
lang_font['bamum'] = ["Noto Sans Bamum"]
lang_font['ilycian'] = ["Noto Sans lLycian"]
lang_font['sylotinagri'] = ["Noto Sans Syloti Nagri"]
lang_font['phagspa'] = ["Noto Sans Phagspa"]
lang_font['canadianaboriginal'] = ["Noto Sans Canadian Aboriginal"]
lang_font['mongolian'] = ["Noto Sans Mongolian"]
lang_font['kaithi'] = [ "Noto Sans Kaithi" ]
lang_font['tibetan'] = [ "Noto Sans Tibetan" ]
lang_font['saurashtra'] = [ "Noto Sans Saurashtra"]
lang_font['lisu'] = ["Noto Sans Lisu"]
lang_font['symbols'] = ["Noto Sans Symbols","Symbola-local"]
lang_font['symbols2'] = ["Noto Sans Symbols 2"]
lang_font['emoji-bw'] = ["Noto Emoji"]
lang_font['emoji-color'] = ["Noto Color Emoji"]
lang_font['syriaceastern'] = ["Noto Sans Syriac Eastern"]
lang_font['buhid'] = ["Noto Sans Buhid"]
lang_font['buginese'] = ["Noto Sans Buginese"]
lang_font['coptic'] = ["Noto Sans Coptic"]
lang_font['syriacwestern'] = ["Noto Sans Syriac Western"]
lang_font['lydian'] = [ "Noto Sans Lydian" ]
lang_font['limbu'] = [ "Noto Sans Limbu" ]
lang_font['syriacestrangela'] = [ "Noto Sans Syriac Estrangela" ]
lang_font['ogham'] = [ "Noto Sans Ogham" ]
lang_font['mandaic'] = [ "Noto Sans Mandaic" ]	
lang_font['oldpersian'] = [ "Noto Sans Old Persian" ]
lang_font['oldsoutharabian'] = [ "Noto Sans Old South Arabian" ]	
lang_font['hanunoo'] = [ "Noto Sans Hanunoo" ]	
lang_font['kharoshthi'] = [ "Noto Sans Kharoshthi" ]	
lang_font['ugaritic'] = [ "Noto Sans Ugaritic" ]
lang_font['imperialaramaic'] = [ "Noto Sans Imperial Aramaic" ]
lang_font['inscriptionalparthian'] = [ "Noto Sans Inscriptional Parthian" ]
lang_font['georgian'] = [ 
	"Noto Sans Georgian",
	"Noto Serif Georgian"       
]
lang_font['meeteimayek'] = [ "Noto Sans Meetei Mayek" ]            
lang_font['balinese'] = [
	"Noto Sans Balinese",
	"Noto Serif Balinese"
]
lang_font['cham'] = ["Noto Sans Cham"]
lang_font['vai'] = ["Noto Sans Vai"]
lang_font['osmanya'] = ["Noto Sans Osmanya"]
lang_font['cherokee'] = ["Noto Sans Cherokee"]
lang_font['armenian'] = [
	"Noto Sans Armenian",
	"Noto Serif Armenian"
]
lang_font['taiviet'] = ["Noto Sans Tai Viet"]
lang_font['taitham'] = ["Noto Sans Tai Tham"]
lang_font['newtailue'] = ["Noto Sans New Tai Lue"]
lang_font['taile'] = ["Noto Sans Tai Le"]
lang_font['lao'] = [
  "Noto Sans Lao",
  "Noto Sans Lao Looped",
  "Noto Serif Lao",
  "Phetsarath"
]    
lang_font['myanmar'] = [
  "Noto Sans Myanmar",
  "Noto Serif Myanmar",
  "Padauk"
 ]           
 lang_font['khmer'] = [    
  "Angkor",
  "Battambang",
  "Bayon",
  "Bokor",
  "Chenla",
  "Content",
  "Dangrek",
  "Fasthand",
  "Freehand",
  "Hanuman",
  "Kantumruy Pro",
  "Kdam Thmor Pro",
  "Khmer",
  "Koh Santepheap",
  "Konkhmer Sleokchher",
  "Koulen",
  "Metal",
  "Moul",
  "Moulpali",
  "Nokora",
  "Noto Sans Khmer",
  "Noto Serif Khmer",
  "Odor Mean Chey",
  "Preahvihear",
  "Siemreap",
  "Suwannaphum",
  "Taprom"
]	
lang_font['thai'] = [
  "Anuphan",
  "Athiti",
  "Bai Jamjuree",
  "Chakra Petch",
  "Charm",
  "Charmonman",
  "Chonburi",
  "Fahkwang",
  "IBM Plex Sans Thai",
  "IBM Plex Sans Thai Looped",
  "Itim",
  "K2D",
  "Kanit",
  "KoHo",
  "Kodchasan",
  "Krub",
  "Maitree",
  "Mali",
  "Mitr",
  "Niramit",
  "Noto Sans Thai",
  "Noto Sans Thai Looped",
  "Noto Serif Thai",
  "Pattaya",
  "Playpen Sans Thai",
  "Pridi",
  "Prompt",
  "Sarabun",
  "Sriracha",
  "Srisakdi",
  "Taviraj",
  "Thasadith",
  "Trirong"
]
lang_font['telugu'] = [
  "Akaya Telivigala",
  "Anek Telugu",
  "Baloo Tammudu 2",
  "Chathura",
  "Dhurjati",
  "Gidugu",
  "Gurajada",
  "Hind Guntur",
  "Lakki Reddy",
  "Mallanna",
  "Mandali",
  "NTR",
  "Noto Sans Telugu",
  "Noto Serif Telugu",
  "Peddana",
  "Ponnala",
  "Ramabhadra",
  "Ramaraja",
  "Ravi Prakash",
  "Sirivennela",
  "Sree Krushnadevaraya",
  "Suranna",
  "Suravaram",
  "Tenali Ramakrishna",
  "Timmana",
  "Tiro Telugu"
]
lang_font['gurmukhi'] = [
  "Anek Gurmukhi",
  "Baloo Paaji 2",
  "BhuTuka Expanded One",
  "Braah One",
  "Langar",
  "Mukta Mahee",
  "Noto Sans Gurmukhi",
  "Noto Serif Gurmukhi",
  "Tiro Gurmukhi"
]
lang_font['malayalam'] = [
  "Anek Malayalam",
  "Arima",
  "Baloo Chettan 2",
  "Chilanka",
  "Gayathri",
  "Manjari",
  "Noto Sans Malayalam",
  "Noto Serif Malayalam"
]                                         
lang_fong['bengali'] = [
  "Alkatra",
  "Anek Bangla",
  "Atma",
  "Baloo Da 2",
  "Galada",
  "Hind Siliguri",
  "Mina",
  "Noto Sans Bengali",
  "Noto Serif Bengali",
  "Tiro Bangla"
]
lang_font['tamil'] = [
  "Anek Tamil",
  "Arima",
  "Baloo Thambi 2",
  "Catamaran",
  "Coiny",
  "Hind Madurai",
  "Karla Tamil Inclined",
  "Karla Tamil Upright",
  "Kavivanar",
  "Meera Inimai",
  "Mukta Malar",
  "Noto Sans Tamil",
  "Noto Serif Tamil",
  "Oi",
  "Pavanam",
  "Tiro Tamil"
]
lang_font['noto-arabic'] = [
  "Noto Kufi Arabic",
  "Noto Naskh Arabic",
  "Noto Sans Arabic",
]
lang_font['arabic'] = [
  "Aref Ruqaa Ink",
  "Badeen Display",
  "Baloo Bhaijaan 2",
  "Beiruti",
  "Blaka",
  "Blaka Hollow",
  "Blaka Ink",
  "Cairo",
  "Cairo Play",
  "Cascadia Code",
  "Cascadia Mono",
  "Changa",
  "El Messiri",
  "Fustat",
  "Gulzar",
  "Handjet",
  "Harmattan",
  "IBM Plex Sans Arabic",
  "Katibeh",
  "Kufam",
  "Lalezar",
  "Lateef",
  "Lemonada",
  "Mada",
  "Marhey",
  "Markazi Text",
  "Mirza",
  "Noto Kufi Arabic",
  "Noto Naskh Arabic",
  "Noto Naskh Arabic UI-local",
  "Noto Nastaliq Urdu",
  "Noto Sans Arabic",
  "Noto Sans Arabic UI-local"
  "Oi",
  "Playpen Sans Arabic",
  "Qahiri",
  "Rakkas",
  "Readex Pro",
  "Reem Kufi",
  "Reem Kufi Fun",
  "Reem Kufi Ink",
  "Rubik",
  "Ruwudu",
  "Scheherazade New",
  "Tajawal",
  "Vazirmatn",
  "Vibes",
  "Zain"
]
lang_font['noto-trad-chinese'] = ["Noto Sans TC"]
lang_font['noto-simple-chinese'] = ["Noto Sans SC"]
lang_font['noto-hongkong'] = ["Noto Sans HK"]
lang_font['noto-korean'] = ["Noto Sans KR"]
lang_font['noto-japanese'] = ["Noto Sans JP"]
lang_font['japanese'] = [
  "Aoboshi One",
  "BIZ UDGothic",
  "BIZ UDMincho",
  "BIZ UDPGothic",
  "BIZ UDPMincho",
  "Cherry Bomb One",
  "Chokokutai",
  "Darumadrop One",
  "Dela Gothic One",
  "DotGothic16",
  "Hachi Maru Pop",
  "Hina Mincho",
  "IBM Plex Sans JP",
  "Kaisei Decol",
  "Kaisei HarunoUmi",
  "Kaisei Opti",
  "Kaisei Tokumin",
  "Kapakana",
  "Kiwi Maru",
  "Klee One",
  "Kosugi",
  "Kosugi Maru",
  "M PLUS 1",
  "M PLUS 1 Code",
  "M PLUS 1p",
  "M PLUS 2",
  "M PLUS Rounded 1c",
  "Mochiy Pop One",
  "Mochiy Pop P One",
  "Monomaniac One",
  "Murecho",
  "New Tegomin",
  "Noto Sans JP",
  "Noto Serif JP",
  "Palette Mosaic",
  "Potta One",
  "Rampart One",
  "Reggae One",
  "Rock 3D",
  "RocknRoll One",
  "Sawarabi Gothic",
  "Sawarabi Mincho",
  "Shippori Antique",
  "Shippori Antique B1",
  "Shippori Mincho",
  "Shippori Mincho B1",
  "Shizuru",
  "Slackside One",
  "Stick",
  "Train One",
  "Tsukimi Rounded",
  "WDXL Lubrifont JP N",
  "Yomogi",
  "Yuji Boku",
  "Yuji Hentaigana Akari",
  "Yuji Hentaigana Akebono",
  "Yuji Mai",
  "Yuji Syuku",
  "Yusei Magic",
  "Zen Antique",
  "Zen Antique Soft",
  "Zen Kaku Gothic Antique",
  "Zen Kaku Gothic New",
  "Zen Kurenaido",
  "Zen Maru Gothic",
  "Zen Old Mincho"
]
lang_font['gujarati'] = [
  "Anek Gujarati",
  "Baloo Bhai 2",
  "Farsan",
  "Hind Vadodara",
  "Kumar One",
  "Kumar One Outline",
  "Mogra",
  "Mukta Vaani",
  "Noto Sans Gujarati",
  "Noto Serif Gujarati",
  "Rasa",
  "Shrikhand"
]
lang_font['sinhala'] = [
  "Abhaya Libre",
  "Gemunu Libre",
  "Maname",
  "Noto Sans Sinhala",
  "Noto Serif Sinhala",
  "Stick No Bills",
  "Yaldevi"
]
lang_font['hebrew'] = [
  "Alef",
  "Amatic SC",
  "Arimo",
  "Assistant",
  "Bellefair",
  "Bona Nova",
  "Bona Nova SC",
  "Cardo",
  "Cascadia Code",
  "Cascadia Mono",
  "Cousine",
  "David Libre",
  "Frank Ruhl Libre",
  "Fredoka",
  "Handjet",
  "Heebo",
  "IBM Plex Sans Hebrew",
  "Karantina",
  "Libertinus Serif",
  "Lunasima",
  "M PLUS 1p",
  "M PLUS Rounded 1c",
  "Miriam Libre",
  "Noto Rashi Hebrew",
  "Noto Sans Hebrew",
  "Noto Serif Hebrew",
  "Open Sans",
  "Playpen Sans Hebrew",
  "Rubik",
  "Rubik 80s Fade",
  "Rubik Beastly",
  "Rubik Broken Fax",
  "Rubik Bubbles",
  "Rubik Burned",
  "Rubik Dirt",
  "Rubik Distressed",
  "Rubik Doodle Shadow",
  "Rubik Doodle Triangles",
  "Rubik Gemstones",
  "Rubik Glitch",
  "Rubik Glitch Pop",
  "Rubik Iso",
  "Rubik Lines",
  "Rubik Maps",
  "Rubik Marker Hatch",
  "Rubik Maze",
  "Rubik Microbe",
  "Rubik Moonrocks",
  "Rubik Pixels",
  "Rubik Puddles",
  "Rubik Scribble",
  "Rubik Spray Paint",
  "Rubik Storm",
  "Rubik Vinyl",
  "Rubik Wet Paint",
  "Secular One",
  "Solitreo",
  "Suez One",
  "Tinos",
  "Varela Round"
]
lang_font['oriya'] = [
  "Alkatra",
  "Anek Odia",
  "Baloo Bhaina 2",
  "Noto Sans Oriya",
  "Noto Serif Oriya"
]
lang_font['korean'] = [
	"kopubbatang",
	"Hanna",
	"Jejuhallasan",   
	"Jejugothic",              
  "Jejumyeongjo", 
	"Black And White Picture",
	"Black Han Sans",
	"Cute Font",
	"Do Hyeon",
	"Dokdo",
	"East Sea Dokdo",
	"Gaegu",
	"Gamja Flower",
	"Gothic A1",
	"Gugi",
	"Hi Melody",
	"Jua",
	"Kirang Haerang",
	"Nanum Brush Script",
	"Nanum Gothic",
	"Nanum Gothic Coding",
	"Nanum Myeongjo",
	"Nanum Pen Script",
	"Noto Sans KR",
	"Noto Serif KR",
	"Poor Story",
	"Single Day",
	"Song Myung",
	"Stylish",
	"Sunflower",
	"Yeon Sung"
]
lang_font['chinese-simplified'] = [
  "Liu Jian Mao Cao",
  "Long Cang",
  "Ma Shan Zheng",
  "Noto Sans SC",
  "Noto Serif SC",
  "WDXL Lubrifont SC",
  "ZCOOL KuaiLe",
  "ZCOOL QingKe HuangYou",
  "ZCOOL XiaoWei",
  "Zhi Mang Xing"
]
lang_font['devanagari'] = [
	"Lohit Devanagari",
 	"Noto Sans Devanagari UI",                   
	"Noto Sans Devanagari"   
	"Amiko",
	"Amita",
	"Arya",
	"Asar",
	"Baloo",
	"Biryani",
	"Cambay",
	"Dekko",
	"Eczar",
	"Glegoo",
	"Halant",
	"Hind",
	"Inknut Antiqua",
	"Jaldi",
	"Kadwa"
	"Kalam",
	"Karma",
	"Khand",
	"Khula",
	"Kurale"
	"Laila",
	"Martel",
	"Martel Sans",
	"Modak",
	"Mukta",
	"Palanquin",
	"Palanquin Dark",
	"Poppins",
	"Pragati Narrow",
	"Rajdhani",
	"Ranga",
	"Rhodium Libre",
	"Rozha One",
	"Sahitya"
	"Sarala",
	"Sarpanch",
	"Sumana",
	"Sura",
	"Teko",
	"Tillana",
	"Vesper Libre",
	"Yantramanav",
	"Yatra One",
]
lang_font['cyrillic-ext'] = [
	"Alegreya",
	"Alegreya SC",
	"Alegreya Sans",
	"Alegreya Sans SC",
	"Alice",
	"Andika",
	"Arimo",
	"Arsenal",
	"Caveat",
	"Comfortaa",
	"Cormorant",
	"Cormorant Garamond",
	"Cormorant Infant",
	"Cormorant SC",
	"Cormorant Unicase",
	"Cousine",
	"Cuprum",
	"Didact Gothic",
	"EB Garamond",
	"Exo 2",
	"Fira Code",
	"Fira Mono",
	"Fira Sans",
	"Fira Sans Condensed",
	"Fira Sans Extra Condensed",
	"Forum",
	"Gabriela",
	"IBM Plex Mono",
	"IBM Plex Sans",
	"IBM Plex Serif",
	"Istok Web",
	"Jura",
	"Kurale",
	"Lobster",
	"Lora",
	"M PLUS 1p",
	"M PLUS Rounded 1c",
	"Merriweather",
	"Montserrat",
	"Montserrat Alternates",
	"Noto Sans",
	"Noto Serif",
	"Nunito",
	"Old Standard TT",
	"Open Sans",
	"Open Sans Condensed",
	"Oranienbaum",
	"Oswald",
	"PT Mono",
	"PT Sans",
	"PT Sans Caption",
	"PT Sans Narrow",
	"PT Serif",
	"PT Serif Caption",
	"Pacifico",
	"Pangolin",
	"Philosopher",
	"Play",
	"Podkova",
	"Prata",
	"Press Start 2P",
	"Roboto",
	"Roboto Condensed",
	"Roboto Mono",
	"Roboto Slab",
	"Scada",
	"Source Code Pro",
	"Source Sans Pro",
	"Tinos",
	"Ubuntu",
	"Ubuntu Condensed",
	"Ubuntu Mono",
	"Vollkorn",
	"Vollkorn SC",
	"Yeseva One"
]	
lang_font['cyrillic'] = [
	"Alegreya",
	"Alegreya SC",
	"Alegreya Sans",
	"Alegreya Sans SC",
	"Alice",
	"Amatic SC",
	"Andika",
	"Anonymous Pro",
	"Arimo",
	"Arsenal",
	"Bad Script",
	"Caveat",
	"Comfortaa",
	"Cormorant",
	"Cormorant Garamond",
	"Cormorant Infant",
	"Cormorant SC",
	"Cormorant Unicase",
	"Cousine",
	"Cuprum",
	"Didact Gothic",
	"EB Garamond",
	"El Messiri",
	"Exo 2",
	"Fira Code",
	"Fira Mono",
	"Fira Sans",
	"Fira Sans Condensed",
	"Fira Sans Extra Condensed",
	"Forum",
	"Gabriela",
	"IBM Plex Mono",
	"IBM Plex Sans",
	"IBM Plex Serif",
	"Istok Web",
	"Jura",
	"Kelly Slab",
	"Kosugi",
	"Kosugi Maru",
	"Kurale",
	"Ledger",
	"Literata",
	"Lobster",
	"Lora",
	"M PLUS 1p",
	"M PLUS Rounded 1c",
	"Marck Script",
	"Marmelad",
	"Merriweather",
	"Montserrat",
	"Montserrat Alternates",
	"Neucha",
	"Noto Sans",
	"Noto Sans SC",
	"Noto Serif",
	"Noto Serif SC",
	"Noto Serif TC",
	"Nunito",
	"Old Standard TT",
	"Open Sans",
	"Open Sans Condensed",
	"Oranienbaum",
	"Oswald",
	"PT Mono",
	"PT Sans",
	"PT Sans Caption",
	"PT Sans Narrow",
	"PT Serif",
	"PT Serif Caption",
	"Pacifico",
	"Pangolin",
	"Pattaya",
	"Philosopher",
	"Play",
	"Playfair Display",
	"Playfair Display SC",
	"Podkova",
	"Poiret One",
	"Prata",
	"Press Start 2P",
	"Roboto Slab",
	"Rubik",
	"Rubik Mono One",
	"Ruslan Display",
	"Russo One",
	"Sawarabi Gothic",
	"Scada",
	"Seymour One",
	"Source Code Pro",
	"Source Sans Pro",
	"Spectral",
	"Spectral SC",
	"Stalinist One",
	"Tenor Sans",
	"Tinos",
	"Ubuntu",
	"Ubuntu Condensed",
	"Ubuntu Mono",
	"Underdog",
	"Vollkorn",
	"Vollkorn SC",
	"Yanone Kaffeesatz",
	"Yeseva One",
];
lang_font['latin'] = [
  "ADLaM Display",
  "AR One Sans",
  "Abel",
  "Abhaya Libre",
  "Aboreto",
  "Abril Fatface",
  "Abyssinica SIL",
  "Aclonica",
  "Acme",
  "Actor",
  "Adamina",
  "Advent Pro",
  "Afacad",
  "Afacad Flux",
  "Agbalumo",
  "Agdasima",
  "Agu Display",
  "Aguafina Script",
  "Akatab",
  "Akaya Kanadaka",
  "Akaya Telivigala",
  "Akronim",
  "Akshar",
  "Aladin",
  "Alan Sans",
  "Alata",
  "Alatsi",
  "Albert Sans",
  "Aldrich",
  "Alef",
  "Alegreya",
  "Alegreya SC",
  "Alegreya Sans",
  "Alegreya Sans SC",
  "Aleo",
  "Alex Brush",
  "Alexandria",
  "Alfa Slab One",
  "Alice",
  "Alike",
  "Alike Angular",
  "Alkalami",
  "Alkatra",
  "Allan",
  "Allerta",
  "Allerta Stencil",
  "Allison",
  "Allura",
  "Almarai",
  "Almendra",
  "Almendra Display",
  "Almendra SC",
  "Alumni Sans",
  "Alumni Sans Collegiate One",
  "Alumni Sans Inline One",
  "Alumni Sans Pinstripe",
  "Alumni Sans SC",
  "Amarante",
  "Amaranth",
  "Amatic SC",
  "Amethysta",
  "Amiko",
  "Amiri",
  "Amiri Quran",
  "Amita",
  "Anaheim",
  "Ancizar Sans",
  "Ancizar Serif",
  "Andada Pro",
  "Andika",
  "Anek Bangla",
  "Anek Devanagari",
  "Anek Gujarati",
  "Anek Gurmukhi",
  "Anek Kannada",
  "Anek Latin",
  "Anek Malayalam",
  "Anek Odia",
  "Anek Tamil",
  "Anek Telugu",
  "Angkor",
  "Annapurna SIL",
  "Annie Use Your Telescope",
  "Anonymous Pro",
  "Anta",
  "Antic",
  "Antic Didone",
  "Antic Slab",
  "Anton",
  "Anton SC",
  "Antonio",
  "Anuphan",
  "Anybody",
  "Aoboshi One",
  "Arapey",
  "Arbutus",
  "Arbutus Slab",
  "Architects Daughter",
  "Archivo",
  "Archivo Black",
  "Archivo Narrow",
  "Are You Serious",
  "Aref Ruqaa",
  "Aref Ruqaa Ink",
  "Arima",
  "Arimo",
  "Arizonia",
  "Armata",
  "Arsenal",
  "Arsenal SC",
  "Artifika",
  "Arvo",
  "Arya",
  "Asap",
  "Asap Condensed",
  "Asar",
  "Asimovian",
  "Asset",
  "Assistant",
  "Asta Sans",
  "Astloch",
  "Asul",
  "Athiti",
  "Atkinson Hyperlegible",
  "Atkinson Hyperlegible Mono",
  "Atkinson Hyperlegible Next",
  "Atma",
  "Atomic Age",
  "Aubrey",
  "Audiowide",
  "Autour One",
  "Average",
  "Average Sans",
  "Averia Gruesa Libre",
  "Averia Libre",
  "Averia Sans Libre",
  "Averia Serif Libre",
  "Azeret Mono",
  "B612",
  "B612 Mono",
  "BIZ UDGothic",
  "BIZ UDMincho",
  "BIZ UDPGothic",
  "BIZ UDPMincho",
  "Babylonica",
  "Bacasime Antique",
  "Bad Script",
  "Badeen Display",
  "Bagel Fat One",
  "Bahiana",
  "Bahianita",
  "Bai Jamjuree",
  "Bakbak One",
  "Ballet",
  "Baloo 2",
  "Baloo Bhai 2",
  "Baloo Bhaijaan 2",
  "Baloo Bhaina 2",
  "Baloo Chettan 2",
  "Baloo Da 2",
  "Baloo Paaji 2",
  "Baloo Tamma 2",
  "Baloo Tammudu 2",
  "Baloo Thambi 2",
  "Balsamiq Sans",
  "Balthazar",
  "Bangers",
  "Barlow",
  "Barlow Condensed",
  "Barlow Semi Condensed",
  "Barriecito",
  "Barrio",
  "Basic",
  "Baskervville",
  "Baskervville SC",
  "Battambang",
  "Baumans",
  "Bayon",
  "Be Vietnam Pro",
  "Beau Rivage",
  "Bebas Neue",
  "Beiruti",
  "Belanosima",
  "Belgrano",
  "Bellefair",
  "Belleza",
  "Bellota",
  "Bellota Text",
  "BenchNine",
  "Benne",
  "Bentham",
  "Berkshire Swash",
  "Besley",
  "Beth Ellen",
  "Bevan",
  "BhuTuka Expanded One",
  "Big Shoulders",
  "Big Shoulders Inline",
  "Big Shoulders Stencil",
  "Bigelow Rules",
  "Bigshot One",
  "Bilbo",
  "Bilbo Swash Caps",
  "BioRhyme",
  "BioRhyme Expanded",
  "Birthstone",
  "Birthstone Bounce",
  "Biryani",
  "Bitcount",
  "Bitcount Grid Double",
  "Bitcount Grid Double Ink",
  "Bitcount Grid Single",
  "Bitcount Grid Single Ink",
  "Bitcount Ink",
  "Bitcount Prop Double",
  "Bitcount Prop Double Ink",
  "Bitcount Prop Single",
  "Bitcount Prop Single Ink",
  "Bitcount Single",
  "Bitcount Single Ink",
  "Bitter",
  "Black And White Picture",
  "Black Han Sans",
  "Black Ops One",
  "Blaka",
  "Blaka Hollow",
  "Blaka Ink",
  "Blinker",
  "Bodoni Moda",
  "Bodoni Moda SC",
  "Bokor",
  "Boldonse",
  "Bona Nova",
  "Bona Nova SC",
  "Bonbon",
  "Bonheur Royale",
  "Boogaloo",
  "Borel",
  "Bowlby One",
  "Bowlby One SC",
  "Braah One",
  "Brawler",
  "Bree Serif",
  "Bricolage Grotesque",
  "Bruno Ace",
  "Bruno Ace SC",
  "Brygada 1918",
  "Bubblegum Sans",
  "Bubbler One",
  "Buda",
  "Buenard",
  "Bungee",
  "Bungee Hairline",
  "Bungee Inline",
  "Bungee Outline",
  "Bungee Shade",
  "Bungee Spice",
  "Bungee Tint",
  "Butcherman",
  "Butterfly Kids",
  "Bytesized",
  "Cabin",
  "Cabin Condensed",
  "Cabin Sketch",
  "Cactus Classical Serif",
  "Caesar Dressing",
  "Cagliostro",
  "Cairo",
  "Cairo Play",
  "Cal Sans",
  "Caladea",
  "Calistoga",
  "Calligraffitti",
  "Cambay",
  "Cambo",
  "Candal",
  "Cantarell",
  "Cantata One",
  "Cantora One",
  "Caprasimo",
  "Capriola",
  "Caramel",
  "Carattere",
  "Cardo",
  "Carlito",
  "Carme",
  "Carrois Gothic",
  "Carrois Gothic SC",
  "Carter One",
  "Cascadia Code",
  "Cascadia Mono",
  "Castoro",
  "Castoro Titling",
  "Catamaran",
  "Caudex",
  "Caveat",
  "Caveat Brush",
  "Cedarville Cursive",
  "Ceviche One",
  "Chakra Petch",
  "Changa",
  "Changa One",
  "Chango",
  "Charis SIL",
  "Charm",
  "Charmonman",
  "Chathura",
  "Chau Philomene One",
  "Chela One",
  "Chelsea Market",
  "Cherish",
  "Cherry Bomb One",
  "Cherry Cream Soda",
  "Cherry Swash",
  "Chewy",
  "Chicle",
  "Chilanka",
  "Chiron GoRound TC",
  "Chiron Hei HK",
  "Chiron Sung HK",
  "Chivo",
  "Chivo Mono",
  "Chocolate Classical Sans",
  "Chokokutai",
  "Chonburi",
  "Cinzel",
  "Cinzel Decorative",
  "Clicker Script",
  "Climate Crisis",
  "Coda",
  "Codystar",
  "Coiny",
  "Combo",
  "Comfortaa",
  "Comforter",
  "Comforter Brush",
  "Comic Neue",
  "Comic Relief",
  "Coming Soon",
  "Comme",
  "Commissioner",
  "Concert One",
  "Condiment",
  "Contrail One",
  "Convergence",
  "Cookie",
  "Copse",
  "Coral Pixels",
  "Corben",
  "Corinthia",
  "Cormorant",
  "Cormorant Garamond",
  "Cormorant Infant",
  "Cormorant SC",
  "Cormorant Unicase",
  "Cormorant Upright",
  "Cossette Texte",
  "Cossette Titre",
  "Courgette",
  "Courier Prime",
  "Cousine",
  "Coustard",
  "Covered By Your Grace",
  "Crafty Girls",
  "Creepster",
  "Crete Round",
  "Crimson Pro",
  "Crimson Text",
  "Croissant One",
  "Crushed",
  "Cuprum",
  "Cute Font",
  "Cutive",
  "Cutive Mono",
  "DM Mono",
  "DM Sans",
  "DM Serif Display",
  "DM Serif Text",
  "Dai Banna SIL",
  "Damion",
  "Dancing Script",
  "Danfo",
  "Dangrek",
  "Darker Grotesque",
  "Darumadrop One",
  "David Libre",
  "Dawning of a New Day",
  "Days One",
  "Dekko",
  "Dela Gothic One",
  "Delicious Handrawn",
  "Delius",
  "Delius Swash Caps",
  "Delius Unicase",
  "Della Respira",
  "Denk One",
  "Devonshire",
  "Dhurjati",
  "Didact Gothic",
  "Diphylleia",
  "Diplomata",
  "Diplomata SC",
  "Do Hyeon",
  "Dokdo",
  "Domine",
  "Donegal One",
  "Dongle",
  "Doppio One",
  "Dorsa",
  "Dosis",
  "DotGothic16",
  "Doto",
  "Dr Sugiyama",
  "Duru Sans",
  "DynaPuff",
  "Dynalight",
  "EB Garamond",
  "Eagle Lake",
  "East Sea Dokdo",
  "Eater",
  "Economica",
  "Eczar",
  "Edu AU VIC WA NT Arrows",
  "Edu AU VIC WA NT Dots",
  "Edu AU VIC WA NT Guides",
  "Edu AU VIC WA NT Hand",
  "Edu AU VIC WA NT Pre",
  "Edu NSW ACT Cursive",
  "Edu NSW ACT Foundation",
  "Edu NSW ACT Hand Pre",
  "Edu QLD Beginner",
  "Edu QLD Hand",
  "Edu SA Beginner",
  "Edu SA Hand",
  "Edu TAS Beginner",
  "Edu VIC WA NT Beginner",
  "Edu VIC WA NT Hand",
  "Edu VIC WA NT Hand Pre",
  "El Messiri",
  "Electrolize",
  "Elsie",
  "Elsie Swash Caps",
  "Emblema One",
  "Emilys Candy",
  "Encode Sans",
  "Encode Sans Condensed",
  "Encode Sans Expanded",
  "Encode Sans SC",
  "Encode Sans Semi Condensed",
  "Encode Sans Semi Expanded",
  "Engagement",
  "Englebert",
  "Enriqueta",
  "Ephesis",
  "Epilogue",
  "Epunda Sans",
  "Epunda Slab",
  "Erica One",
  "Esteban",
  "Estonia",
  "Euphoria Script",
  "Ewert",
  "Exile",
  "Exo",
  "Exo 2",
  "Expletus Sans",
  "Explora",
  "Faculty Glyphic",
  "Fahkwang",
  "Familjen Grotesk",
  "Fanwood Text",
  "Farro",
  "Farsan",
  "Fascinate",
  "Fascinate Inline",
  "Faster One",
  "Fasthand",
  "Fauna One",
  "Faustina",
  "Federant",
  "Federo",
  "Felipa",
  "Fenix",
  "Festive",
  "Figtree",
  "Finger Paint",
  "Finlandica",
  "Fira Code",
  "Fira Mono",
  "Fira Sans",
  "Fira Sans Condensed",
  "Fira Sans Extra Condensed",
  "Fjalla One",
  "Fjord One",
  "Flamenco",
  "Flavors",
  "Fleur De Leah",
  "Flow Block",
  "Flow Circular",
  "Flow Rounded",
  "Foldit",
  "Fondamento",
  "Fontdiner Swanky",
  "Forum",
  "Fragment Mono",
  "Francois One",
  "Frank Ruhl Libre",
  "Fraunces",
  "Freckle Face",
  "Fredericka the Great",
  "Fredoka",
  "Freehand",
  "Freeman",
  "Fresca",
  "Frijole",
  "Fruktur",
  "Fugaz One",
  "Fuggles",
  "Funnel Display",
  "Funnel Sans",
  "Fustat",
  "Fuzzy Bubbles",
  "GFS Didot",
  "GFS Neohellenic",
  "Ga Maamli",
  "Gabarito",
  "Gabriela",
  "Gaegu",
  "Gafata",
  "Gajraj One",
  "Galada",
  "Galdeano",
  "Galindo",
  "Gamja Flower",
  "Gantari",
  "Gasoek One",
  "Gayathri",
  "Geist",
  "Geist Mono",
  "Gelasio",
  "Gemunu Libre",
  "Genos",
  "Gentium Book Plus",
  "Gentium Plus",
  "Geo",
  "Geologica",
  "Georama",
  "Geostar",
  "Geostar Fill",
  "Germania One",
  "Gideon Roman",
  "Gidole",
  "Gidugu",
  "Gilda Display",
  "Girassol",
  "Give You Glory",
  "Glass Antiqua",
  "Glegoo",
  "Gloock",
  "Gloria Hallelujah",
  "Glory",
  "Gluten",
  "Goblin One",
  "Gochi Hand",
  "Goldman",
  "Golos Text",
  "Google Sans Code",
  "Gorditas",
  "Gothic A1",
  "Gotu",
  "Goudy Bookletter 1911",
  "Gowun Batang",
  "Gowun Dodum",
  "Graduate",
  "Grand Hotel",
  "Grandiflora One",
  "Grandstander",
  "Grape Nuts",
  "Gravitas One",
  "Great Vibes",
  "Grechen Fuemen",
  "Grenze",
  "Grenze Gotisch",
  "Grey Qo",
  "Griffy",
  "Gruppo",
  "Gudea",
  "Gugi",
  "Gulzar",
  "Gupter",
  "Gurajada",
  "Gwendolyn",
  "Habibi",
  "Hachi Maru Pop",
  "Hahmlet",
  "Halant",
  "Hammersmith One",
  "Hanalei",
  "Hanalei Fill",
  "Handjet",
  "Handlee",
  "Hanken Grotesk",
  "Hanuman",
  "Happy Monkey",
  "Harmattan",
  "Headland One",
  "Hedvig Letters Sans",
  "Hedvig Letters Serif",
  "Heebo",
  "Henny Penny",
  "Hepta Slab",
  "Herr Von Muellerhoff",
  "Hi Melody",
  "Hina Mincho",
  "Hind",
  "Hind Guntur",
  "Hind Madurai",
  "Hind Mysuru",
  "Hind Siliguri",
  "Hind Vadodara",
  "Holtwood One SC",
  "Homemade Apple",
  "Homenaje",
  "Honk",
  "Host Grotesk",
  "Hubballi",
  "Hubot Sans",
  "Huninn",
  "Hurricane",
  "Iansui",
  "Ibarra Real Nova",
  "Iceberg",
  "Iceland",
  "Imbue",
  "Imperial Script",
  "Imprima",
  "Inclusive Sans",
  "Inconsolata",
  "Inder",
  "Indie Flower",
  "Ingrid Darling",
  "Inika",
  "Inknut Antiqua",
  "Inria Sans",
  "Inria Serif",
  "Inspiration",
  "Instrument Sans",
  "Instrument Serif",
  "Intel One Mono",
  "Inter",
  "Inter Tight",
  "Irish Grover",
  "Island Moments",
  "Istok Web",
  "Italiana",
  "Italianno",
  "Itim",
  "Jacquard 12",
  "Jacquard 12 Charted",
  "Jacquard 24",
  "Jacquard 24 Charted",
  "Jacquarda Bastarda 9",
  "Jacquarda Bastarda 9 Charted",
  "Jacques Francois",
  "Jacques Francois Shadow",
  "Jaini",
  "Jaini Purva",
  "Jaldi",
  "Jaro",
  "Jersey 10",
  "Jersey 10 Charted",
  "Jersey 15",
  "Jersey 15 Charted",
  "Jersey 20",
  "Jersey 20 Charted",
  "Jersey 25",
  "Jersey 25 Charted",
  "JetBrains Mono",
  "Jim Nightshade",
  "Joan",
  "Jockey One",
  "Jolly Lodger",
  "Jomhuria",
  "Jomolhari",
  "Josefin Sans",
  "Josefin Slab",
  "Jost",
  "Joti One",
  "Jua",
  "Judson",
  "Julee",
  "Julius Sans One",
  "Junge",
  "Jura",
  "Just Another Hand",
  "Just Me Again Down Here",
  "K2D",
  "Kablammo",
  "Kadwa",
  "Kaisei Decol",
  "Kaisei HarunoUmi",
  "Kaisei Opti",
  "Kaisei Tokumin",
  "Kalam",
  "Kalnia",
  "Kalnia Glaze",
  "Kameron",
  "Kanchenjunga",
  "Kanit",
  "Kantumruy Pro",
  "Kapakana",
  "Karantina",
  "Karla",
  "Karma",
  "Katibeh",
  "Kaushan Script",
  "Kavivanar",
  "Kavoon",
  "Kay Pho Du",
  "Kdam Thmor Pro",
  "Keania One",
  "Kelly Slab",
  "Kenia",
  "Khand",
  "Khula",
  "Kings",
  "Kirang Haerang",
  "Kite One",
  "Kiwi Maru",
  "Klee One",
  "Knewave",
  "KoHo",
  "Kodchasan",
  "Kode Mono",
  "Koh Santepheap",
  "Kolker Brush",
  "Konkhmer Sleokchher",
  "Kosugi",
  "Kosugi Maru",
  "Kotta One",
  "Koulen",
  "Kranky",
  "Kreon",
  "Kristi",
  "Krona One",
  "Krub",
  "Kufam",
  "Kulim Park",
  "Kumar One",
  "Kumar One Outline",
  "Kumbh Sans",
  "Kurale",
  "LXGW Marker Gothic",
  "LXGW WenKai Mono TC",
  "LXGW WenKai TC",
  "La Belle Aurore",
  "Labrada",
  "Lacquer",
  "Laila",
  "Lakki Reddy",
  "Lalezar",
  "Lancelot",
  "Langar",
  "Lateef",
  "Lato",
  "Lavishly Yours",
  "League Gothic",
  "League Script",
  "League Spartan",
  "Leckerli One",
  "Ledger",
  "Lekton",
  "Lemon",
  "Lemonada",
  "Lexend",
  "Lexend Deca",
  "Lexend Exa",
  "Lexend Giga",
  "Lexend Mega",
  "Lexend Peta",
  "Lexend Tera",
  "Lexend Zetta",
  "Libertinus Keyboard",
  "Libertinus Math",
  "Libertinus Mono",
  "Libertinus Sans",
  "Libertinus Serif",
  "Libertinus Serif Display",
  "Libre Barcode 128",
  "Libre Barcode 128 Text",
  "Libre Barcode 39",
  "Libre Barcode 39 Extended",
  "Libre Barcode 39 Extended Text",
  "Libre Barcode 39 Text",
  "Libre Barcode EAN13 Text",
  "Libre Baskerville",
  "Libre Bodoni",
  "Libre Caslon Display",
  "Libre Caslon Text",
  "Libre Franklin",
  "Licorice",
  "Life Savers",
  "Lilita One",
  "Lily Script One",
  "Limelight",
  "Linden Hill",
  "Linefont",
  "Lisu Bosa",
  "Liter",
  "Literata",
  "Liu Jian Mao Cao",
  "Livvic",
  "Lobster",
  "Lobster Two",
  "Londrina Outline",
  "Londrina Shadow",
  "Londrina Sketch",
  "Londrina Solid",
  "Long Cang",
  "Lora",
  "Love Light",
  "Love Ya Like A Sister",
  "Loved by the King",
  "Lovers Quarrel",
  "Luckiest Guy",
  "Lugrasimo",
  "Lumanosimo",
  "Lunasima",
  "Lusitana",
  "Lustria",
  "Luxurious Roman",
  "Luxurious Script",
  "M PLUS 1",
  "M PLUS 1 Code",
  "M PLUS 1p",
  "M PLUS 2",
  "M PLUS Code Latin",
  "M PLUS Rounded 1c",
  "Ma Shan Zheng",
  "Macondo",
  "Macondo Swash Caps",
  "Mada",
  "Madimi One",
  "Magra",
  "Maiden Orange",
  "Maitree",
  "Major Mono Display",
  "Mako",
  "Mali",
  "Mallanna",
  "Maname",
  "Mandali",
  "Manjari",
  "Manrope",
  "Mansalva",
  "Manuale",
  "Manufacturing Consent",
  "Marcellus",
  "Marcellus SC",
  "Marck Script",
  "Margarine",
  "Marhey",
  "Markazi Text",
  "Marko One",
  "Marmelad",
  "Martel",
  "Martel Sans",
  "Martian Mono",
  "Marvel",
  "Matangi",
  "Mate",
  "Mate SC",
  "Matemasie",
  "Material Icons",
  "Material Icons Outlined",
  "Material Icons Round",
  "Material Icons Sharp",
  "Material Icons Two Tone",
  "Material Symbols",
  "Material Symbols Outlined",
  "Material Symbols Rounded",
  "Material Symbols Sharp",
  "Maven Pro",
  "McLaren",
  "Mea Culpa",
  "Meddon",
  "MedievalSharp",
  "Medula One",
  "Meera Inimai",
  "Megrim",
  "Meie Script",
  "Menbere",
  "Meow Script",
  "Merienda",
  "Merriweather",
  "Merriweather Sans",
  "Metal",
  "Metal Mania",
  "Metamorphous",
  "Metrophobic",
  "Michroma",
  "Micro 5",
  "Micro 5 Charted",
  "Milonga",
  "Miltonian",
  "Miltonian Tattoo",
  "Mina",
  "Mingzat",
  "Miniver",
  "Miriam Libre",
  "Mirza",
  "Miss Fajardose",
  "Mitr",
  "Mochiy Pop One",
  "Mochiy Pop P One",
  "Modak",
  "Modern Antiqua",
  "Moderustic",
  "Mogra",
  "Mohave",
  "Moirai One",
  "Molengo",
  "Molle",
  "Mona Sans",
  "Monda",
  "Monofett",
  "Monomakh",
  "Monomaniac One",
  "Monoton",
  "Monsieur La Doulaise",
  "Montaga",
  "Montagu Slab",
  "MonteCarlo",
  "Montez",
  "Montserrat",
  "Montserrat Alternates",
  "Montserrat Underline",
  "Moo Lah Lah",
  "Mooli",
  "Moon Dance",
  "Moul",
  "Moulpali",
  "Mountains of Christmas",
  "Mouse Memoirs",
  "Mozilla Headline",
  "Mozilla Text",
  "Mr Bedfort",
  "Mr Dafoe",
  "Mr De Haviland",
  "Mrs Saint Delafield",
  "Mrs Sheppards",
  "Ms Madi",
  "Mukta",
  "Mukta Mahee",
  "Mukta Malar",
  "Mukta Vaani",
  "Mulish",
  "Murecho",
  "MuseoModerno",
  "My Soul",
  "Mynerve",
  "Mystery Quest",
  "NTR",
  "Nabla",
  "Namdhinggo",
  "Nanum Brush Script",
  "Nanum Gothic",
  "Nanum Gothic Coding",
  "Nanum Myeongjo",
  "Nanum Pen Script",
  "Narnoor",
  "Nata Sans",
  "National Park",
  "Neonderthaw",
  "Nerko One",
  "Neucha",
  "Neuton",
  "New Amsterdam",
  "New Rocker",
  "New Tegomin",
  "News Cycle",
  "Newsreader",
  "Niconne",
  "Niramit",
  "Nixie One",
  "Nobile",
  "Nokora",
  "Norican",
  "Nosifer",
  "Notable",
  "Nothing You Could Do",
  "Noticia Text",
  "Noto Sans",
  "Noto Serif",
  "Nova Cut",
  "Nova Flat",
  "Nova Mono",
  "Nova Oval",
  "Nova Round",
  "Nova Script",
  "Nova Slim",
  "Nova Square",
  "Numans",
  "Nunito",
  "Nunito Sans",
  "Nuosu SIL",
  "Odibee Sans",
  "Odor Mean Chey",
  "Offside",
  "Oi",
  "Ojuju",
  "Old Standard TT",
  "Oldenburg",
  "Ole",
  "Oleo Script",
  "Oleo Script Swash Caps",
  "Onest",
  "Oooh Baby",
  "Open Sans",
  "Oranienbaum",
  "Orbit",
  "Orbitron",
  "Oregano",
  "Orelega One",
  "Orienta",
  "Original Surfer",
  "Oswald",
  "Outfit",
  "Over the Rainbow",
  "Overlock",
  "Overlock SC",
  "Overpass",
  "Overpass Mono",
  "Ovo",
  "Oxanium",
  "Oxygen",
  "Oxygen Mono",
  "PT Mono",
  "PT Sans",
  "PT Sans Caption",
  "PT Sans Narrow",
  "PT Serif",
  "PT Serif Caption",
  "Pacifico",
  "Padauk",
  "Padyakke Expanded One",
  "Palanquin",
  "Palanquin Dark",
  "Palette Mosaic",
  "Pangolin",
  "Paprika",
  "Parastoo",
  "Parisienne",
  "Parkinsans",
  "Passero One",
  "Passion One",
  "Passions Conflict",
  "Pathway Extreme",
  "Pathway Gothic One",
  "Patrick Hand",
  "Patrick Hand SC",
  "Pattaya",
  "Patua One",
  "Pavanam",
  "Paytone One",
  "Peddana",
  "Peralta",
  "Permanent Marker",
  "Petemoss",
  "Petit Formal Script",
  "Petrona",
  "Philosopher",
  "Phudu",
  "Piazzolla",
  "Piedra",
  "Pinyon Script",
  "Pirata One",
  "Pixelify Sans",
  "Plaster",
  "Platypi",
  "Play",
  "Playball",
  "Playfair",
  "Playfair Display",
  "Playfair Display SC",
  "Playpen Sans",
  "Playwrite US Modern",
  "Playwrite US Trad",
  "Plus Jakarta Sans",
  "Pochaevsk",
  "Podkova",
  "Poetsen One",
  "Poiret One",
  "Poller One",
  "Poltawski Nowy",
  "Poly",
  "Pompiere",
  "Ponnala",
  "Ponomar",
  "Pontano Sans",
  "Poor Story",
  "Poppins",
  "Port Lligat Sans",
  "Port Lligat Slab",
  "Potta One",
  "Pragati Narrow",
  "Praise",
  "Prata",
  "Preahvihear",
  "Press Start 2P",
  "Pridi",
  "Princess Sofia",
  "Prociono",
  "Prompt",
  "Prosto One",
  "Protest Guerrilla",
  "Protest Revolution",
  "Protest Riot",
  "Protest Strike",
  "Proza Libre",
  "Public Sans",
  "Puppies Play",
  "Puritan",
  "Purple Purse",
  "Qahiri",
  "Quando",
  "Quantico",
  "Quattrocento",
  "Quattrocento Sans",
  "Questrial",
  "Quicksand",
  "Quintessential",
  "Qwigley",
  "Qwitcher Grypen",
  "REM",
  "Racing Sans One",
  "Radio Canada",
  "Radio Canada Big",
  "Radley",
  "Rajdhani",
  "Rakkas",
  "Raleway",
  "Raleway Dots",
  "Ramabhadra",
  "Ramaraja",
  "Rambla",
  "Rammetto One",
  "Rampart One",
  "Ranchers",
  "Rancho",
  "Ranga",
  "Rasa",
  "Rationale",
  "Ravi Prakash",
  "Readex Pro",
  "Recursive",
  "Red Hat Display",
  "Red Hat Mono",
  "Red Hat Text",
  "Red Rose",
  "Redacted",
  "Redacted Script",
  "Reddit Mono",
  "Reddit Sans",
  "Reddit Sans Condensed",
  "Redressed",
  "Reem Kufi",
  "Reem Kufi Fun",
  "Reem Kufi Ink",
  "Reenie Beanie",
  "Reggae One",
  "Rethink Sans",
  "Revalia",
  "Rhodium Libre",
  "Ribeye",
  "Ribeye Marrow",
  "Righteous",
  "Risque",
  "Road Rage",
  "Roboto",
  "Roboto Condensed",
  "Roboto Flex",
  "Roboto Mono",
  "Roboto Serif",
  "Roboto Slab",
  "Rochester",
  "Rock 3D",
  "Rock Salt",
  "RocknRoll One",
  "Rokkitt",
  "Romanesco",
  "Ropa Sans",
  "Rosario",
  "Rosarivo",
  "Rouge Script",
  "Rowdies",
  "Rozha One",
  "Rubik",
  "Rubik 80s Fade",
  "Rubik Beastly",
  "Rubik Broken Fax",
  "Rubik Bubbles",
  "Rubik Burned",
  "Rubik Dirt",
  "Rubik Distressed",
  "Rubik Doodle Shadow",
  "Rubik Doodle Triangles",
  "Rubik Gemstones",
  "Rubik Glitch",
  "Rubik Glitch Pop",
  "Rubik Iso",
  "Rubik Lines",
  "Rubik Maps",
  "Rubik Marker Hatch",
  "Rubik Maze",
  "Rubik Microbe",
  "Rubik Mono One",
  "Rubik Moonrocks",
  "Rubik Pixels",
  "Rubik Puddles",
  "Rubik Scribble",
  "Rubik Spray Paint",
  "Rubik Storm",
  "Rubik Vinyl",
  "Rubik Wet Paint",
  "Ruda",
  "Rufina",
  "Ruge Boogie",
  "Ruluko",
  "Rum Raisin",
  "Ruslan Display",
  "Russo One",
  "Ruthie",
  "Ruwudu",
  "Rye",
  "STIX Two Text",
  "SUSE",
  "SUSE Mono",
  "Sacramento",
  "Sahitya",
  "Sail",
  "Saira",
  "Saira Condensed",
  "Saira Extra Condensed",
  "Saira Semi Condensed",
  "Saira Stencil One",
  "Salsa",
  "Sanchez",
  "Sancreek",
  "Sankofa Display",
  "Sansation",
  "Sansita",
  "Sansita Swashed",
  "Sarabun",
  "Sarala",
  "Sarina",
  "Sarpanch",
  "Sassy Frass",
  "Satisfy",
  "Savate",
  "Sawarabi Gothic",
  "Sawarabi Mincho",
  "Scada",
  "Scheherazade New",
  "Schibsted Grotesk",
  "Schoolbell",
  "Scope One",
  "Seaweed Script",
  "Secular One",
  "Sedan",
  "Sedan SC",
  "Sedgwick Ave",
  "Sedgwick Ave Display",
  "Sen",
  "Send Flowers",
  "Sevillana",
  "Seymour One",
  "Shadows Into Light",
  "Shadows Into Light Two",
  "Shafarik",
  "Shalimar",
  "Shantell Sans",
  "Shanti",
  "Share",
  "Share Tech",
  "Share Tech Mono",
  "Shippori Antique",
  "Shippori Antique B1",
  "Shippori Mincho",
  "Shippori Mincho B1",
  "Shizuru",
  "Shojumaru",
  "Short Stack",
  "Shrikhand",
  "Sigmar",
  "Sigmar One",
  "Signika",
  "Signika Negative",
  "Silkscreen",
  "Simonetta",
  "Sintony",
  "Sirin Stencil",
  "Sirivennela",
  "Six Caps",
  "Sixtyfour",
  "Sixtyfour Convergence",
  "Skranji",
  "Slabo 13px",
  "Slabo 27px",
  "Slackey",
  "Slackside One",
  "Smokum",
  "Smooch",
  "Smooch Sans",
  "Smythe",
  "Sniglet",
  "Snippet",
  "Snowburst One",
  "Sofadi One",
  "Sofia",
  "Sofia Sans",
  "Sofia Sans Condensed",
  "Sofia Sans Extra Condensed",
  "Sofia Sans Semi Condensed",
  "Solitreo",
  "Solway",
  "Sometype Mono",
  "Sono",
  "Sonsie One",
  "Sora",
  "Sorts Mill Goudy",
  "Sour Gummy",
  "Source Code Pro",
  "Source Sans 3",
  "Source Serif 4",
  "Space Grotesk",
  "Space Mono",
  "Special Elite",
  "Special Gothic",
  "Special Gothic Condensed One",
  "Special Gothic Expanded One",
  "Spectral",
  "Spectral SC",
  "Spicy Rice",
  "Spinnaker",
  "Spirax",
  "Splash",
  "Spline Sans",
  "Spline Sans Mono",
  "Squada One",
  "Square Peg",
  "Sree Krushnadevaraya",
  "Sriracha",
  "Srisakdi",
  "Staatliches",
  "Stalemate",
  "Stalinist One",
  "Stardos Stencil",
  "Stick",
  "Stick No Bills",
  "Stint Ultra Condensed",
  "Stint Ultra Expanded",
  "Stoke",
  "Story Script",
  "Strait",
  "Style Script",
  "Sue Ellen Francisco",
  "Suez One",
  "Sulphur Point",
  "Sumana",
  "Sunshiney",
  "Supermercado One",
  "Sura",
  "Suranna",
  "Suravaram",
  "Suwannaphum",
  "Swanky and Moo Moo",
  "Syncopate",
  "Syne",
  "Syne Mono",
  "Syne Tactile",
  "TASA Explorer",
  "TASA Orbiter",
  "Tac One",
  "Tagesschrift",
  "Tai Heritage Pro",
  "Tajawal",
  "Tangerine",
  "Tapestry",
  "Taprom",
  "Tauri",
  "Taviraj",
  "Teachers",
  "Teko",
  "Tektur",
  "Telex",
  "Tenali Ramakrishna",
  "Tenor Sans",
  "Text Me One",
  "Texturina",
  "Thasadith",
  "The Girl Next Door",
  "The Nautigal",
  "Tienne",
  "TikTok Sans",
  "Tillana",
  "Tilt Neon",
  "Tilt Prism",
  "Tilt Warp",
  "Timmana",
  "Tinos",
  "Tiny5",
  "Tiro Bangla",
  "Tirra",
  "Titan One",
  "Titillium Web",
  "Tomorrow",
  "Tourney",
  "Trade Winds",
  "Train One",
  "Triodion",
  "Trirong",
  "Trispace",
  "Trocchi",
  "Trochut",
  "Truculenta",
  "Trykker",
  "Tsukimi Rounded",
  "Tuffy",
  "Tulpen One",
  "Turret Road",
  "Twinkle Star",
  "Ubuntu",
  "Ubuntu Condensed",
  "Ubuntu Mono",
  "Ubuntu Sans",
  "Ubuntu Sans Mono",
  "Uchen",
  "Ultra",
  "Unbounded",
  "Uncial Antiqua",
  "Underdog",
  "Unica One",
  "UnifrakturCook",
  "UnifrakturMaguntia",
  "Unkempt",
  "Unlock",
  "Unna",
  "UoqMunThenKhung",
  "Updock",
  "Urbanist",
  "VT323",
  "Vampiro One",
  "Varela",
  "Varela Round",
  "Varta",
  "Vast Shadow",
  "Vazirmatn",
  "Vend Sans",
  "Vesper Libre",
  "Viaoda Libre",
  "Vibes",
  "Vibur",
  "Victor Mono",
  "Vidaloka",
  "Viga",
  "Vina Sans",
  "Voces",
  "Volkhov",
  "Vollkorn",
  "Vollkorn SC",
  "Voltaire",
  "Vujahday Script",
  "Waiting for the Sunrise",
  "Wallpoet",
  "Walter Turncoat",
  "Warnes",
  "Water Brush",
  "Waterfall",
  "Wavefont",
  "Wellfleet",
  "Wendy One",
  "Whisper",
  "WindSong",
  "Winky Rough",
  "Winky Sans",
  "Wire One",
  "Wittgenstein",
  "Wix Madefor Display",
  "Wix Madefor Text",
  "Work Sans",
  "Workbench",
  "Xanh Mono",
  "Yaldevi",
  "Yanone Kaffeesatz",
  "Yantramanav",
  "Yarndings 12",
  "Yarndings 12 Charted",
  "Yarndings 20",
  "Yarndings 20 Charted",
  "Yatra One",
  "Yellowtail",
  "Yeon Sung",
  "Yeseva One",
  "Yesteryear",
  "Yomogi",
  "Young Serif",
  "Yrsa",
  "Ysabeau",
  "Ysabeau Infant",
  "Ysabeau Office",
  "Ysabeau SC",
  "Yuji Boku",
  "Yusei Magic",
  "ZCOOL KuaiLe",
  "ZCOOL QingKe HuangYou",
  "ZCOOL XiaoWei",
  "Zain",
  "Zalando Sans",
  "Zalando Sans Expanded",
  "Zalando Sans SemiExpanded",
  "Zen Antique",
  "Zen Antique Soft",
  "Zen Dots",
  "Zen Kaku Gothic Antique",
  "Zen Kaku Gothic New",
  "Zen Kurenaido",
  "Zen Loop",
  "Zen Maru Gothic",
  "Zen Old Mincho",
  "Zen Tokyo Zoo",
  "Zeyada",
  "Zhi Mang Xing",
  "Zilla Slab",
  "Zilla Slab Highlight"
]
lang_fong['latin-ext'] = [
  "ADLaM Display",
  "AR One Sans",
  "Abhaya Libre",
  "Aboreto",
  "Abril Fatface",
  "Abyssinica SIL",
  "Aclonica",
  "Advent Pro",
  "Afacad",
  "Afacad Flux",
  "Agbalumo",
  "Agdasima",
  "Agu Display",
  "Aguafina Script",
  "Akatab",
  "Akaya Kanadaka",
  "Akaya Telivigala",
  "Akronim",
  "Akshar",
  "Aladin",
  "Alan Sans",
  "Alata",
  "Alatsi",
  "Albert Sans",
  "Alegreya",
  "Alegreya SC",
  "Alegreya Sans",
  "Alegreya Sans SC",
  "Aleo",
  "Alex Brush",
  "Alexandria",
  "Alfa Slab One",
  "Alice",
  "Alike",
  "Alike Angular",
  "Alkalami",
  "Alkatra",
  "Allan",
  "Allison",
  "Allura",
  "Almendra",
  "Almendra Display",
  "Alumni Sans",
  "Alumni Sans Collegiate One",
  "Alumni Sans Inline One",
  "Alumni Sans Pinstripe",
  "Alumni Sans SC",
  "Amarante",
  "Amatic SC",
  "Amiko",
  "Amiri",
  "Amita",
  "Anaheim",
  "Ancizar Sans",
  "Ancizar Serif",
  "Andada Pro",
  "Andika",
  "Anek Bangla",
  "Anek Devanagari",
  "Anek Gujarati",
  "Anek Gurmukhi",
  "Anek Kannada",
  "Anek Latin",
  "Anek Malayalam",
  "Anek Odia",
  "Anek Tamil",
  "Anek Telugu",
  "Annapurna SIL",
  "Annie Use Your Telescope",
  "Anonymous Pro",
  "Anta",
  "Anton",
  "Anton SC",
  "Antonio",
  "Anuphan",
  "Anybody",
  "Aoboshi One",
  "Arbutus",
  "Arbutus Slab",
  "Architects Daughter",
  "Archivo",
  "Archivo Black",
  "Archivo Narrow",
  "Are You Serious",
  "Aref Ruqaa",
  "Aref Ruqaa Ink",
  "Arima",
  "Arimo",
  "Arizonia",
  "Armata",
  "Arsenal",
  "Arsenal SC",
  "Arya",
  "Asap",
  "Asap Condensed",
  "Asar",
  "Asimovian",
  "Asset",
  "Assistant",
  "Athiti",
  "Atkinson Hyperlegible",
  "Atkinson Hyperlegible Mono",
  "Atkinson Hyperlegible Next",
  "Atma",
  "Atomic Age",
  "Audiowide",
  "Autour One",
  "Average",
  "Average Sans",
  "Averia Gruesa Libre",
  "Azeret Mono",
  "BIZ UDGothic",
  "BIZ UDMincho",
  "BIZ UDPGothic",
  "BIZ UDPMincho",
  "Babylonica",
  "Bacasime Antique",
  "Bad Script",
  "Badeen Display",
  "Bagel Fat One",
  "Bahiana",
  "Bahianita",
  "Bai Jamjuree",
  "Bakbak One",
  "Ballet",
  "Baloo 2",
  "Baloo Bhai 2",
  "Baloo Bhaijaan 2",
  "Baloo Bhaina 2",
  "Baloo Chettan 2",
  "Baloo Da 2",
  "Baloo Paaji 2",
  "Baloo Tamma 2",
  "Baloo Tammudu 2",
  "Baloo Thambi 2",
  "Balsamiq Sans",
  "Bangers",
  "Barlow",
  "Barlow Condensed",
  "Barlow Semi Condensed",
  "Barriecito",
  "Barrio",
  "Basic",
  "Baskervville",
  "Baskervville SC",
  "Be Vietnam Pro",
  "Beau Rivage",
  "Bebas Neue",
  "Beiruti",
  "Belanosima",
  "Bellefair",
  "Belleza",
  "Bellota",
  "Bellota Text",
  "BenchNine",
  "Benne",
  "Bentham",
  "Berkshire Swash",
  "Besley",
  "Bevan",
  "BhuTuka Expanded One",
  "Big Shoulders",
  "Big Shoulders Inline",
  "Big Shoulders Stencil",
  "Bigelow Rules",
  "Bilbo",
  "Bilbo Swash Caps",
  "BioRhyme",
  "BioRhyme Expanded",
  "Birthstone",
  "Birthstone Bounce",
  "Biryani",
  "Bitcount",
  "Bitcount Grid Double",
  "Bitcount Grid Double Ink",
  "Bitcount Grid Single",
  "Bitcount Grid Single Ink",
  "Bitcount Ink",
  "Bitcount Prop Double",
  "Bitcount Prop Double Ink",
  "Bitcount Prop Single",
  "Bitcount Prop Single Ink",
  "Bitcount Single",
  "Bitcount Single Ink",
  "Bitter",
  "Black Ops One",
  "Blaka",
  "Blaka Hollow",
  "Blaka Ink",
  "Blinker",
  "Bodoni Moda",
  "Bodoni Moda SC",
  "Boldonse",
  "Bona Nova",
  "Bona Nova SC",
  "Bonheur Royale",
  "Borel",
  "Bowlby One SC",
  "Braah One",
  "Bree Serif",
  "Bricolage Grotesque",
  "Bruno Ace",
  "Bruno Ace SC",
  "Brygada 1918",
  "Bubblegum Sans",
  "Bubbler One",
  "Buenard",
  "Bungee",
  "Bungee Hairline",
  "Bungee Inline",
  "Bungee Outline",
  "Bungee Shade",
  "Bungee Spice",
  "Bungee Tint",
  "Butcherman",
  "Butterfly Kids",
  "Bytesized",
  "Cabin",
  "Cabin Condensed",
  "Cactus Classical Serif",
  "Cairo",
  "Cairo Play",
  "Cal Sans",
  "Caladea",
  "Calistoga",
  "Cambay",
  "Cambo",
  "Cantarell",
  "Cantata One",
  "Cantora One",
  "Caprasimo",
  "Capriola",
  "Caramel",
  "Carattere",
  "Cardo",
  "Carlito",
  "Cascadia Code",
  "Cascadia Mono",
  "Castoro",
  "Castoro Titling",
  "Catamaran",
  "Caudex",
  "Caveat",
  "Caveat Brush",
  "Ceviche One",
  "Chakra Petch",
  "Changa",
  "Chango",
  "Charis SIL",
  "Charm",
  "Charmonman",
  "Chau Philomene One",
  "Chela One",
  "Chelsea Market",
  "Cherish",
  "Cherry Bomb One",
  "Cherry Swash",
  "Chicle",
  "Chilanka",
  "Chiron GoRound TC",
  "Chiron Hei HK",
  "Chiron Sung HK",
  "Chivo",
  "Chivo Mono",
  "Chocolate Classical Sans",
  "Chokokutai",
  "Chonburi",
  "Cinzel",
  "Cinzel Decorative",
  "Clicker Script",
  "Climate Crisis",
  "Coda",
  "Codystar",
  "Coiny",
  "Combo",
  "Comfortaa",
  "Comforter",
  "Comforter Brush",
  "Comic Relief",
  "Comme",
  "Commissioner",
  "Concert One",
  "Condiment",
  "Convergence",
  "Coral Pixels",
  "Corben",
  "Corinthia",
  "Cormorant",
  "Cormorant Garamond",
  "Cormorant Infant",
  "Cormorant SC",
  "Cormorant Unicase",
  "Cormorant Upright",
  "Cossette Texte",
  "Cossette Titre",
  "Courgette",
  "Courier Prime",
  "Cousine",
  "Covered By Your Grace",
  "Crete Round",
  "Crimson Pro",
  "Crimson Text",
  "Croissant One",
  "Crushed",
  "Cuprum",
  "Cutive",
  "Cutive Mono",
  "DM Mono",
  "DM Sans",
  "DM Serif Display",
  "DM Serif Text",
  "Dai Banna SIL",
  "Damion",
  "Dancing Script",
  "Danfo",
  "Darker Grotesque",
  "Darumadrop One",
  "David Libre",
  "Dekko",
  "Dela Gothic One",
  "Delicious Handrawn",
  "Denk One",
  "Devonshire",
  "Didact Gothic",
  "Diphylleia",
  "Diplomata",
  "Diplomata SC",
  "Domine",
  "Donegal One",
  "Dongle",
  "Doppio One",
  "Dosis",
  "DotGothic16",
  "Doto",
  "Dr Sugiyama",
  "Duru Sans",
  "DynaPuff",
  "Dynalight",
  "EB Garamond",
  "Eagle Lake",
  "Eater",
  "Economica",
  "Eczar",
  "Edu AU VIC WA NT Arrows",
  "Edu AU VIC WA NT Dots",
  "Edu AU VIC WA NT Guides",
  "Edu AU VIC WA NT Hand",
  "Edu AU VIC WA NT Pre",
  "Edu NSW ACT Cursive",
  "Edu NSW ACT Hand Pre",
  "Edu QLD Hand",
  "Edu SA Hand",
  "Edu VIC WA NT Hand",
  "Edu VIC WA NT Hand Pre",
  "El Messiri",
  "Elsie",
  "Elsie Swash Caps",
  "Emblema One",
  "Emilys Candy",
  "Encode Sans",
  "Encode Sans Condensed",
  "Encode Sans Expanded",
  "Encode Sans SC",
  "Encode Sans Semi Condensed",
  "Encode Sans Semi Expanded",
  "Engagement",
  "Englebert",
  "Enriqueta",
  "Ephesis",
  "Epilogue",
  "Epunda Sans",
  "Epunda Slab",
  "Erica One",
  "Esteban",
  "Estonia",
  "Euphoria Script",
  "Ewert",
  "Exile",
  "Exo",
  "Exo 2",
  "Expletus Sans",
  "Explora",
  "Faculty Glyphic",
  "Fahkwang",
  "Familjen Grotesk",
  "Fanwood Text",
  "Farro",
  "Farsan",
  "Fascinate",
  "Fascinate Inline",
  "Faster One",
  "Fauna One",
  "Faustina",
  "Felipa",
  "Fenix",
  "Festive",
  "Figtree",
  "Finlandica",
  "Fira Code",
  "Fira Mono",
  "Fira Sans",
  "Fira Sans Condensed",
  "Fira Sans Extra Condensed",
  "Fjalla One",
  "Flavors",
  "Fleur De Leah",
  "Flow Block",
  "Flow Circular",
  "Flow Rounded",
  "Foldit",
  "Fondamento",
  "Forum",
  "Fragment Mono",
  "Francois One",
  "Frank Ruhl Libre",
  "Fraunces",
  "Freckle Face",
  "Fredericka the Great",
  "Fredoka",
  "Freeman",
  "Fresca",
  "Fruktur",
  "Fuggles",
  "Funnel Display",
  "Funnel Sans",
  "Fustat",
  "Fuzzy Bubbles",
  "Ga Maamli",
  "Gabarito",
  "Gabriela",
  "Gafata",
  "Gajraj One",
  "Galindo",
  "Gantari",
  "Gasoek One",
  "Geist",
  "Geist Mono",
  "Gelasio",
  "Gemunu Libre",
  "Genos",
  "Gentium Book Plus",
  "Gentium Plus",
  "Geologica",
  "Georama",
  "Gideon Roman",
  "Gidole",
  "Gidugu",
  "Gilda Display",
  "Girassol",
  "Give You Glory",
  "Glass Antiqua",
  "Glegoo",
  "Gloock",
  "Gloria Hallelujah",
  "Glory",
  "Gluten",
  "Goldman",
  "Golos Text",
  "Google Sans Code",
  "Gothic A1",
  "Gotu",
  "Gowun Batang",
  "Gowun Dodum",
  "Grand Hotel",
  "Grandiflora One",
  "Grandstander",
  "Grape Nuts",
  "Great Vibes",
  "Grechen Fuemen",
  "Grenze",
  "Grenze Gotisch",
  "Grey Qo",
  "Griffy",
  "Gruppo",
  "Gudea",
  "Gulzar",
  "Gurajada",
  "Gwendolyn",
  "Habibi",
  "Hachi Maru Pop",
  "Hahmlet",
  "Halant",
  "Hammersmith One",
  "Hanalei",
  "Hanalei Fill",
  "Handjet",
  "Hanken Grotesk",
  "Happy Monkey",
  "Harmattan",
  "Headland One",
  "Hedvig Letters Sans",
  "Hedvig Letters Serif",
  "Heebo",
  "Hepta Slab",
  "Herr Von Muellerhoff",
  "Hina Mincho",
  "Hind",
  "Hind Guntur",
  "Hind Madurai",
  "Hind Mysuru",
  "Hind Siliguri",
  "Hind Vadodara",
  "Holtwood One SC",
  "Honk",
  "Host Grotesk",
  "Hubballi",
  "Hubot Sans",
  "Huninn",
  "Hurricane",
  "IBM Plex Mono",
  "IBM Plex Sans",
  "IBM Plex Sans Arabic",
  "IBM Plex Sans Condensed",
  "IBM Plex Sans Devanagari",
  "IBM Plex Sans Hebrew",
  "IBM Plex Sans JP",
  "IBM Plex Sans KR",
  "IBM Plex Sans Thai",
  "IBM Plex Sans Thai Looped",
  "IBM Plex Serif",
  "Iansui",
  "Ibarra Real Nova",
  "Imbue",
  "Imperial Script",
  "Imprima",
  "Inclusive Sans",
  "Inconsolata",
  "Inder",
  "Indie Flower",
  "Ingrid Darling",
  "Inika",
  "Inknut Antiqua",
  "Inria Sans",
  "Inria Serif",
  "Inspiration",
  "Instrument Sans",
  "Instrument Serif",
  "Intel One Mono",
  "Inter",
  "Inter Tight",
  "Island Moments",
  "Istok Web",
  "Italianno",
  "Itim",
  "Jacquard 12",
  "Jacquard 12 Charted",
  "Jacquard 24",
  "Jacquard 24 Charted",
  "Jacquarda Bastarda 9",
  "Jacquarda Bastarda 9 Charted",
  "Jaini",
  "Jaini Purva",
  "Jaldi",
  "Jaro",
  "Jersey 10",
  "Jersey 10 Charted",
  "Jersey 15",
  "Jersey 15 Charted",
  "Jersey 20",
  "Jersey 20 Charted",
  "Jersey 25",
  "Jersey 25 Charted",
  "JetBrains Mono",
  "Jim Nightshade",
  "Joan",
  "Jockey One",
  "Jolly Lodger",
  "Jomhuria",
  "Josefin Sans",
  "Jost",
  "Joti One",
  "Judson",
  "Julee",
  "Julius Sans One",
  "Jura",
  "Just Another Hand",
  "Just Me Again Down Here",
  "K2D",
  "Kablammo",
  "Kaisei Decol",
  "Kaisei HarunoUmi",
  "Kaisei Opti",
  "Kaisei Tokumin",
  "Kalam",
  "Kalnia",
  "Kalnia Glaze",
  "Kameron",
  "Kanit",
  "Kantumruy Pro",
  "Kapakana",
  "Karantina",
  "Karla",
  "Karma",
  "Katibeh",
  "Kaushan Script",
  "Kavivanar",
  "Kavoon",
  "Kay Pho Du",
  "Kdam Thmor Pro",
  "Keania One",
  "Kelly Slab",
  "Khand",
  "Khula",
  "Kings",
  "Kite One",
  "Kiwi Maru",
  "Klee One",
  "Knewave",
  "KoHo",
  "Kodchasan",
  "Kode Mono",
  "Kolker Brush",
  "Konkhmer Sleokchher",
  "Kosugi",
  "Kosugi Maru",
  "Kotta One",
  "Kreon",
  "Krona One",
  "Krub",
  "Kufam",
  "Kulim Park",
  "Kumar One",
  "Kumar One Outline",
  "Kumbh Sans",
  "Kurale",
  "LXGW Marker Gothic",
  "LXGW WenKai Mono TC",
  "LXGW WenKai TC",
  "La Belle Aurore",
  "Labrada",
  "Laila",
  "Lalezar",
  "Lancelot",
  "Langar",
  "Lateef",
  "Lato",
  "Lavishly Yours",
  "League Gothic",
  "League Spartan",
  "Ledger",
  "Lekton",
  "Lemon",
  "Lemonada",
  "Lexend",
  "Lexend Deca",
  "Lexend Exa",
  "Lexend Giga",
  "Lexend Mega",
  "Lexend Peta",
  "Lexend Tera",
  "Lexend Zetta",
  "Libertinus Keyboard",
  "Libertinus Math",
  "Libertinus Mono",
  "Libertinus Sans",
  "Libertinus Serif",
  "Libertinus Serif Display",
  "Libre Baskerville",
  "Libre Bodoni",
  "Libre Caslon Display",
  "Libre Caslon Text",
  "Libre Franklin",
  "Licorice",
  "Life Savers",
  "Lilita One",
  "Lily Script One",
  "Limelight",
  "Linden Hill",
  "Lisu Bosa",
  "Liter",
  "Literata",
  "Livvic",
  "Lobster",
  "Lora",
  "Love Light",
  "Love Ya Like A Sister",
  "Loved by the King",
  "Lovers Quarrel",
  "Luckiest Guy",
  "Lugrasimo",
  "Lumanosimo",
  "Lunasima",
  "Luxurious Roman",
  "Luxurious Script",
  "M PLUS 1",
  "M PLUS 1 Code",
  "M PLUS 1p",
  "M PLUS 2",
  "M PLUS Code Latin",
  "M PLUS Rounded 1c",
  "Mada",
  "Madimi One",
  "Magra",
  "Maiden Orange",
  "Maitree",
  "Major Mono Display",
  "Mako",
  "Mali",
  "Maname",
  "Manjari",
  "Manrope",
  "Mansalva",
  "Manuale",
  "Manufacturing Consent",
  "Marcellus",
  "Marcellus SC",
  "Marck Script",
  "Margarine",
  "Marhey",
  "Markazi Text",
  "Marmelad",
  "Martel",
  "Martel Sans",
  "Martian Mono",
  "Matangi",
  "Mate",
  "Mate SC",
  "Matemasie",
  "Maven Pro",
  "McLaren",
  "Mea Culpa",
  "Meddon",
  "MedievalSharp",
  "Megrim",
  "Meie Script",
  "Menbere",
  "Meow Script",
  "Merienda",
  "Merriweather",
  "Merriweather Sans",
  "Metal Mania",
  "Metamorphous",
  "Metrophobic",
  "Michroma",
  "Micro 5",
  "Micro 5 Charted",
  "Milonga",
  "Mina",
  "Mingzat",
  "Miriam Libre",
  "Mirza",
  "Miss Fajardose",
  "Mitr",
  "Modak",
  "Modern Antiqua",
  "Moderustic",
  "Mogra",
  "Mohave",
  "Moirai One",
  "Molengo",
  "Molle",
  "Mona Sans",
  "Monda",
  "Monofett",
  "Monomakh",
  "Monomaniac One",
  "Monoton",
  "Monsieur La Doulaise",
  "Montagu Slab",
  "MonteCarlo",
  "Montez",
  "Montserrat",
  "Montserrat Alternates",
  "Montserrat Underline",
  "Moo Lah Lah",
  "Mooli",
  "Moon Dance",
  "Mouse Memoirs",
  "Mozilla Headline",
  "Mozilla Text",
  "Mr Bedfort",
  "Mr Dafoe",
  "Mr De Haviland",
  "Mrs Saint Delafield",
  "Mrs Sheppards",
  "Ms Madi",
  "Mukta",
  "Mukta Mahee",
  "Mukta Malar",
  "Mukta Vaani",
  "Mulish",
  "Murecho",
  "MuseoModerno",
  "My Soul",
  "Mynerve",
  "Mystery Quest",
  "Nabla",
  "Namdhinggo",
  "Narnoor",
  "Nata Sans",
  "National Park",
  "Neonderthaw",
  "Nerko One",
  "Neuton",
  "New Amsterdam",
  "New Rocker",
  "New Tegomin",
  "News Cycle",
  "Newsreader",
  "Niconne",
  "Niramit",
  "Nobile",
  "Norican",
  "Nosifer",
  "Noticia Text",
  "Noto Sans",
  "Noto Serif",
  "Nova Cut",
  "Nova Flat",
  "Nova Mono",
  "Nova Oval",
  "Nova Round",
  "Nova Script",
  "Nova Slim",
  "Nova Square",
  "Nunito",
  "Nunito Sans",
  "Nuosu SIL",
  "Offside",
  "Oi",
  "Ojuju",
  "Old Standard TT",
  "Oldenburg",
  "Ole",
  "Oleo Script",
  "Oleo Script Swash Caps",
  "Onest",
  "Oooh Baby",
  "Open Sans",
  "Oranienbaum",
  "Orbit",
  "Oregano",
  "Orelega One",
  "Orienta",
  "Original Surfer",
  "Oswald",
  "Outfit",
  "Over the Rainbow",
  "Overlock",
  "Overlock SC",
  "Overpass",
  "Overpass Mono",
  "Oxanium",
  "Oxygen",
  "Oxygen Mono",
  "PT Mono",
  "PT Sans",
  "PT Sans Caption",
  "PT Sans Narrow",
  "PT Serif",
  "PT Serif Caption",
  "Pacifico",
  "Padauk",
  "Padyakke Expanded One",
  "Palanquin",
  "Palanquin Dark",
  "Pangolin",
  "Paprika",
  "Parastoo",
  "Parisienne",
  "Parkinsans",
  "Passero One",
  "Passion One",
  "Passions Conflict",
  "Pathway Extreme",
  "Pathway Gothic One",
  "Patrick Hand",
  "Patrick Hand SC",
  "Pattaya",
  "Pavanam",
  "Paytone One",
  "Peralta",
  "Petemoss",
  "Petit Formal Script",
  "Petrona",
  "Philosopher",
  "Phudu",
  "Piazzolla",
  "Piedra",
  "Pinyon Script",
  "Pirata One",
  "Pixelify Sans",
  "Plaster",
  "Platypi",
  "Play",
  "Playball",
  "Playfair",
  "Playfair Display",
  "Playfair Display SC",
  "Playpen Sans",
  "Plus Jakarta Sans",
  "Podkova",
  "Poetsen One",
  "Poiret One",
  "Poltawski Nowy",
  "Poly",
  "Pontano Sans",
  "Poppins",
  "Potta One",
  "Pragati Narrow",
  "Praise",
  "Press Start 2P",
  "Pridi",
  "Princess Sofia",
  "Prompt",
  "Prosto One",
  "Protest Guerrilla",
  "Protest Revolution",
  "Protest Riot",
  "Protest Strike",
  "Proza Libre",
  "Public Sans",
  "Puppies Play",
  "Purple Purse",
  "Quando",
  "Quattrocento",
  "Quattrocento Sans",
  "Questrial",
  "Quicksand",
  "Quintessential",
  "Qwigley",
  "Qwitcher Grypen",
  "REM",
  "Racing Sans One",
  "Radio Canada",
  "Radio Canada Big",
  "Radley",
  "Rajdhani",
  "Rakkas",
  "Raleway",
  "Raleway Dots",
  "Rambla",
  "Rammetto One",
  "Rampart One",
  "Ranchers",
  "Ranga",
  "Rasa",
  "Readex Pro",
  "Recursive",
  "Red Hat Display",
  "Red Hat Mono",
  "Red Hat Text",
  "Red Rose",
  "Redacted",
  "Redacted Script",
  "Reddit Mono",
  "Reddit Sans",
  "Reddit Sans Condensed",
  "Redressed",
  "Reem Kufi",
  "Reem Kufi Fun",
  "Reem Kufi Ink",
  "Reggae One",
  "Rethink Sans",
  "Revalia",
  "Rhodium Libre",
  "Ribeye",
  "Ribeye Marrow",
  "Righteous",
  "Risque",
  "Road Rage",
  "Roboto",
  "Roboto Condensed",
  "Roboto Flex",
  "Roboto Mono",
  "Roboto Serif",
  "Roboto Slab",
  "RocknRoll One",
  "Rokkitt",
  "Romanesco",
  "Ropa Sans",
  "Rosario",
  "Rosarivo",
  "Rowdies",
  "Rozha One",
  "Rubik",
  "Rubik 80s Fade",
  "Rubik Beastly",
  "Rubik Broken Fax",
  "Rubik Bubbles",
  "Rubik Burned",
  "Rubik Dirt",
  "Rubik Distressed",
  "Rubik Doodle Shadow",
  "Rubik Doodle Triangles",
  "Rubik Gemstones",
  "Rubik Glitch",
  "Rubik Glitch Pop",
  "Rubik Iso",
  "Rubik Lines",
  "Rubik Maps",
  "Rubik Marker Hatch",
  "Rubik Maze",
  "Rubik Microbe",
  "Rubik Mono One",
  "Rubik Moonrocks",
  "Rubik Pixels",
  "Rubik Puddles",
  "Rubik Scribble",
  "Rubik Spray Paint",
  "Rubik Storm",
  "Rubik Vinyl",
  "Rubik Wet Paint",
  "Ruda",
  "Rufina",
  "Ruge Boogie",
  "Ruluko",
  "Rum Raisin",
  "Ruslan Display",
  "Russo One",
  "Ruthie",
  "Ruwudu",
  "Rye",
  "STIX Two Text",
  "SUSE",
  "SUSE Mono",
  "Sacramento",
  "Sail",
  "Saira",
  "Saira Condensed",
  "Saira Extra Condensed",
  "Saira Semi Condensed",
  "Saira Stencil One",
  "Sanchez",
  "Sancreek",
  "Sankofa Display",
  "Sansation",
  "Sansita",
  "Sansita Swashed",
  "Sarabun",
  "Sarala",
  "Sarina",
  "Sarpanch",
  "Sassy Frass",
  "Savate",
  "Sawarabi Gothic",
  "Sawarabi Mincho",
  "Scada",
  "Scheherazade New",
  "Schibsted Grotesk",
  "Scope One",
  "Seaweed Script",
  "Secular One",
  "Sedan",
  "Sedan SC",
  "Sedgwick Ave",
  "Sedgwick Ave Display",
  "Sen",
  "Send Flowers",
  "Sevillana",
  "Seymour One",
  "Shadows Into Light",
  "Shadows Into Light Two",
  "Shafarik",
  "Shalimar",
  "Shantell Sans",
  "Shanti",
  "Share",
  "Shippori Antique",
  "Shippori Antique B1",
  "Shippori Mincho",
  "Shippori Mincho B1",
  "Shojumaru",
  "Shrikhand",
  "Sigmar",
  "Sigmar One",
  "Signika",
  "Signika Negative",
  "Silkscreen",
  "Simonetta",
  "Sintony",
  "Six Caps",
  "Sixtyfour",
  "Sixtyfour Convergence",
  "Skranji",
  "Slabo 13px",
  "Slabo 27px",
  "Slackside One",
  "Smokum",
  "Smooch",
  "Smooch Sans",
  "Sniglet",
  "Snowburst One",
  "Sofia Sans",
  "Sofia Sans Condensed",
  "Sofia Sans Extra Condensed",
  "Sofia Sans Semi Condensed",
  "Solitreo",
  "Sometype Mono",
  "Sono",
  "Sonsie One",
  "Sora",
  "Sorts Mill Goudy",
  "Sour Gummy",
  "Source Code Pro",
  "Source Sans 3",
  "Source Serif 4",
  "Space Grotesk",
  "Space Mono",
  "Special Elite",
  "Special Gothic",
  "Special Gothic Condensed One",
  "Special Gothic Expanded One",
  "Spectral",
  "Spectral SC",
  "Spicy Rice",
  "Spinnaker",
  "Splash",
  "Spline Sans",
  "Spline Sans Mono",
  "Square Peg",
  "Sriracha",
  "Srisakdi",
  "Staatliches",
  "Stalemate",
  "Stalinist One",
  "Stick",
  "Stick No Bills",
  "Stint Ultra Condensed",
  "Stint Ultra Expanded",
  "Stoke",
  "Story Script",
  "Strait",
  "Style Script",
  "Suez One",
  "Sulphur Point",
  "Sumana",
  "Supermercado One",
  "Sura",
  "Swanky and Moo Moo",
  "Syncopate",
  "Syne",
  "Syne Mono",
  "Syne Tactile",
  "TASA Explorer",
  "TASA Orbiter",
  "Tac One",
  "Tagesschrift",
  "Tai Heritage Pro",
  "Tapestry",
  "Tauri",
  "Taviraj",
  "Teachers",
  "Teko",
  "Tektur",
  "Telex",
  "Tenor Sans",
  "Text Me One",
  "Texturina",
  "Thasadith",
  "The Girl Next Door",
  "The Nautigal",
  "TikTok Sans",
  "Tillana",
  "Tilt Neon",
  "Tilt Prism",
  "Tilt Warp",
  "Tinos",
  "Tiny5",
  "Tiro Bangla",
  "Tirra",
  "Titan One",
  "Titillium Web",
  "Tomorrow",
  "Tourney",
  "Train One",
  "Trirong",
  "Trispace",
  "Trocchi",
  "Truculenta",
  "Trykker",
  "Tsukimi Rounded",
  "Tuffy",
  "Turret Road",
  "Twinkle Star",
  "Ubuntu",
  "Ubuntu Condensed",
  "Ubuntu Mono",
  "Ubuntu Sans",
  "Ubuntu Sans Mono",
  "Ultra",
  "Unbounded",
  "Uncial Antiqua",
  "Underdog",
  "Unica One",
  "Unlock",
  "Unna",
  "Updock",
  "Urbanist",
  "VT323",
  "Vampiro One",
  "Varela",
  "Varela Round",
  "Varta",
  "Vazirmatn",
  "Vend Sans",
  "Vesper Libre",
  "Viaoda Libre",
  "Victor Mono",
  "Viga",
  "Vina Sans",
  "Voces",
  "Vollkorn",
  "Vollkorn SC",
  "Voltaire",
  "Vujahday Script",
  "WDXL Lubrifont JP N",
  "WDXL Lubrifont SC",
  "WDXL Lubrifont TC",
  "Waiting for the Sunrise",
  "Warnes",
  "Water Brush",
  "Waterfall",
  "Wellfleet",
  "Wendy One",
  "Whisper",
  "WindSong",
  "Winky Rough",
  "Winky Sans",
  "Wittgenstein",
  "Wix Madefor Display",
  "Wix Madefor Text",
  "Work Sans",
  "Xanh Mono",
  "Yaldevi",
  "Yanone Kaffeesatz",
  "Yantramanav",
  "Yatra One",
  "Yellowtail",
  "Yeseva One",
  "Yesteryear",
  "Yomogi",
  "Young Serif",
  "Yrsa",
  "Ysabeau",
  "Ysabeau Infant",
  "Ysabeau Office",
  "Ysabeau SC",
  "Yuji Boku",
  "Yuji Hentaigana Akari",
  "Yuji Hentaigana Akebono",
  "Yuji Mai",
  "Yuji Syuku",
  "Yusei Magic",
  "Zalando Sans",
  "Zalando Sans Expanded",
  "Zalando Sans SemiExpanded",
  "Zen Antique",
  "Zen Antique Soft",
  "Zen Dots",
  "Zen Kaku Gothic Antique",
  "Zen Kaku Gothic New",
  "Zen Kurenaido",
  "Zen Loop",
  "Zen Maru Gothic",
  "Zen Old Mincho",
  "Zen Tokyo Zoo",
  "Zeyada",
  "Zilla Slab",
  "Zilla Slab Highlight"
]