var_blocks_list = [
  "Arabic",
  "Armenian",
  "Basic Latin",
  "Bengali",
  "CJK Unified Ideographs",
  "Cherokee",
  "Cyrillic",
  "Cyrillic Extended-B",
  "Devanagari",
  "Ethiopic",
  "Geometric Shapes",
  "Georgian",
  "Greek Extended",
  "Greek and Coptic",
  "Gujarati",
  "Gurmukhi",
  "Hangul Syllables",
  "Hebrew",
  "Hiragana",
  "Kannada",
  "Khmer",
  "Lao",
  "Latin Extended-A",
  "Latin Extended-B",
  "Makasar",
  "Malayalam",
  "Mathematical Operators",
  "Myanmar",
  "Oriya",
  "Sinhala",
  "Syriac",
  "Tai Le",
  "Tamil",
  "Telugu",
  "Thai",
  "Tibetan",
  "Tifinagh",
  "Znamenny Musical Notation"
];

