var_blocks_list = [
  "Adlam",
  "Arabic",
  "Armenian",
  "Basic Latin",
  "Bassa Vah",
  "Bengali",
  "CJK Unified Ideographs",
  "Cham",
  "Cherokee",
  "Cyrillic",
  "Cyrillic Extended-B",
  "Devanagari",
  "Ethiopic",
  "Geometric Shapes",
  "Georgian",
  "Greek Extended",
  "Greek and Coptic",
  "Gujarati",
  "Gunjala Gondi",
  "Gurmukhi",
  "Hangul Syllables",
  "Hanifi Rohingya",
  "Hebrew",
  "Hentaigana",
  "Hiragana",
  "Kannada",
  "Kawi",
  "Kayah Li",
  "Khmer",
  "Khojki",
  "Lao",
  "Latin Extended-A",
  "Latin Extended-B",
  "Lisu",
  "Malayalam",
  "Mathematical Operators",
  "Medefaidrin",
  "Meetei Mayek",
  "NP Hmong",
  "Nag Mundari",
  "New Tai Lue",
  "NKo",
  "Nushu",
  "Ol Chiki",
  "Oriya",
  "Sinhala",
  "Sora Sompeng",
  "Sundanese",
  "Symbols",
  "Syriac",
  "Tai Tham",
  "Tamil",
  "Tangsa",
  "Telugu",
  "Thai",
  "Tibetan",
  "Tifinagh",
  "Toto",
  "Unified Canadian Aboriginal Syllabics",
  "Vithkuqi",
  "Yezidi"
];
console.log('var_blocks_list loaded');
var_blocks_listWait = true;
